Import('OS_ROOT')
Import('osconfig')
from build_tools import *

pwd = PresentDir()

src = ['nxp_devices.c']

path =  [pwd]

group = AddCodeGroup('hal/devices', src, depend = ['SOC_FAMILY_NXP_LPC'], CPPPATH = path)

Return('group')
