from build_tools import *

pwd     = PresentDir()
src     = ['timer.c']

if IsDefined('OS_USING_CLOCKSOURCE'):
    src += ['clocksource.c']

if IsDefined('OS_USING_CLOCKSOURCE_CORTEXM'):
    src += ['clocksource_cortexm.c']
    
if IsDefined('OS_USING_CLOCKEVENT'):
    src += ['clockevent.c']
    
if IsDefined('OS_USING_HRTIMER'):
    src += ['hrtimer.c']
    
if IsDefined('OS_USING_TIMEKEEPING'):
    src += ['timekeeping.c']
    
group   = AddCodeGroup('drivers', src, depend = ['OS_USING_TIMER_DRIVER'], CPPPATH = [pwd])

Return('group')
