Import('osconfig')
from build_tools import *

pwd  = PresentDir()
src  = []
group = []
path = []

if IsDefined(['ARCH_XTENSA_LX6']) == False:
    Return('group')

if osconfig.COMPILER == 'gcc':
    src += Glob('*.c')
    src += Glob('*_gcc.S')  
 

group = AddCodeGroup('cpu', src, depend = [''], CPPPATH = path)

Return('group')
