from build_tools import *
import osconfig

# get current directory
cwd     = PresentDir()
# The set of source files associated with this SConscript file.
src    = Glob('*.c')
path   = [cwd]

LOCAL_CCFLAGS = ''

if osconfig.CROSS_TOOL == 'gcc':
    LOCAL_CCFLAGS += ' -std=c99'
elif osconfig.CROSS_TOOL == 'keil':
    LOCAL_CCFLAGS += ' --c99 --gnu'

group = AddCodeGroup('mpy_device', src, depend = ['PKG_MICROPYTHON_DEVICE'], CPPPATH = path, LOCAL_CCFLAGS = LOCAL_CCFLAGS)

Return('group')
