import osconfig
Import('OS_ROOT')
from build_tools import *

pwd = PresentDir()
path = [pwd + '/CMSIS/Include',pwd + '/MIMXRT1052', pwd + '/MIMXRT1052/drivers']
src = Split('''
            MIMXRT1052/system_MIMXRT1052.c
            MIMXRT1052/drivers/fsl_common.c
            MIMXRT1052/drivers/fsl_clock.c
            MIMXRT1052/drivers/fsl_cache.c
            ''')

if IsDefined(['BSP_USING_GPIO']):
    src += ['MIMXRT1052/drivers/fsl_gpio.c']

if IsDefined(['BSP_USING_LPUART']):
    src += ['MIMXRT1052/drivers/fsl_lpuart.c']

if IsDefined(['BSP_USING_I2C']):
    src += ['MIMXRT1052/drivers/fsl_lpi2c.c']

if IsDefined(['BSP_USING_SPI']):
    src += ['MIMXRT1052/drivers/fsl_lpspi.c']

if IsDefined(['BSP_USING_HWTIMER']) or IsDefined(['BSP_USING_PWM']):
    src += ['MIMXRT1052/drivers/fsl_gpt.c']

if IsDefined(['BSP_USING_PWM']):
    src += ['MIMXRT1052/drivers/fsl_pwm.c']

if IsDefined(['BSP_USING_RTC']):
    src += ['MIMXRT1052/drivers/fsl_snvs_hp.c']
    src += ['MIMXRT1052/drivers/fsl_snvs_lp.c']

if IsDefined(['BSP_USING_WDT']):
    src += ['MIMXRT1052/drivers/fsl_wdog.c']
    src += ['MIMXRT1052/drivers/fsl_rtwdog.c']

if IsDefined(['BSP_USING_ADC']):
    src += ['MIMXRT1052/drivers/fsl_adc.c']

if IsDefined(['BSP_USING_SDRAM']):
    src += ['MIMXRT1052/drivers/fsl_semc.c']

if IsDefined(['BSP_USING_LCD']):
    src += ['MIMXRT1052/drivers/fsl_elcdif.c']

if IsDefined(['RT_USING_USB_HOST']) or IsDefined(['RT_USING_USB_DEVICE']):
    src += ['MIMXRT1052/drivers/fsl_usdhc.c']

if IsDefined(['BSP_USING_CAN']):
    src += ['MIMXRT1052/drivers/fsl_flexcan.c']

if IsDefined(['BSP_USING_ETH']):
    src += ['MIMXRT1052/drivers/fsl_enet.c']

if IsDefined(['RT_USING_SDIO']):
    src += ['MIMXRT1052/drivers/']

if IsDefined(['RT_USING_AUDIO']):
    src += ['MIMXRT1052/drivers/fsl_sai.c']

if IsDefined(['BSP_USING_LTDC']):
    src += ['MIMXRT1052/drivers/']

if IsDefined(['BSP_USING_DMA']):
    src += ['MIMXRT1052/drivers/fsl_dmamux.c']
    src += ['MIMXRT1052/drivers/fsl_edma.c']
    src += ['MIMXRT1052/drivers/fsl_lpuart_edma.c']
    src += ['MIMXRT1052/drivers/fsl_lpspi_edma.c']

group = AddCodeGroup('hal/lowlevel', src, depend = ['SOC_FAMILY_IMX'], CPPPATH = path)

Return('group')
