Import('OS_ROOT')
from build_tools import *

pwd     = PresentDir()
src     = []
CPPPATH = [pwd + '/include']

if IsDefined('OS_USING_CPU_USAGE') or IsDefined('OS_USING_TASK_MONITOR'):
    src += ['source/resource_monitor.c']


group = AddCodeGroup('diagnose', src, depend = [''], CPPPATH = CPPPATH)

Return('group')

