/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v8.0
processor: LPC55S69
package_id: LPC55S69JBD100
mcu_data: ksdk2_0
processor_version: 8.0.3
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: 4ee6b10f-6049-46b3-bcba-8ff7b946f43d
  called_from_default_init: true
  selectedCore: cm33_core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'system'
- type_id: 'system_54b53072540eeeb8f8e9343e71f28176'
- global_system_definitions:
  - user_definitions: ''
  - user_includes: ''
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "peripherals.h"

/***********************************************************************************************************************
 * BOARD_InitPeripherals functional group
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * DMA0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'DMA0'
- type: 'lpc_dma'
- mode: 'basic'
- custom_name_enabled: 'false'
- type_id: 'lpc_dma_c13ca997a68f2ca6c666916ba13db7d7'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'DMA0'
- config_sets:
  - fsl_dma:
    - dma_table:
      - 0: []
      - 1: []
      - 2: []
      - 3: []
      - 4: []
      - 5: []
      - 6: []
      - 7: []
    - dma_channels:
      - 0:
        - apiMode: 'trans'
        - dma_channel:
          - channel_prefix_id: 'CH0'
          - DMA_source: 'kDma0RequestHashCrypt'
          - init_channel_priority: 'false'
          - dma_priority: 'kDMA_ChannelPriority0'
          - enable_custom_name: 'false'
        - peripheral_request: 'false'
        - init_trigger_config: 'false'
        - trigger_config:
          - type: 'kDMA_NoTrigger'
          - burst: 'kDMA_SingleTransfer'
          - wrap: 'kDMA_NoWrap'
        - trans_config:
          - init_callback: 'false'
          - callback_function: ''
          - callback_user_data: ''
        - tcd_config: []
        - allocateTCD: 'noncache'
        - initTCD: 'noTCDInit'
    - dma_interrupt_trans:
      - IRQn: 'DMA0_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
    - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

  /* Channel CH0 global variables */
dma_handle_t DMA0_CH0_Handle;

static void DMA0_init(void) {

  /* Channel CH0 initialization */
  /* Enable the DMA 0channel in the DMA */
  DMA_EnableChannel(DMA0_DMA_BASEADDR, DMA0_CH0_DMA_CHANNEL);
  /* Create the DMA DMA0_CH0_Handlehandle */
  DMA_CreateHandle(&DMA0_CH0_Handle, DMA0_DMA_BASEADDR, DMA0_CH0_DMA_CHANNEL);
}

/***********************************************************************************************************************
 * ADC0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'ADC0'
- type: 'lpadc'
- mode: 'LPADC'
- custom_name_enabled: 'false'
- type_id: 'lpadc_37e603c0367b4bb173ded9b76a178984'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'ADC0'
- config_sets:
  - fsl_lpadc:
    - lpadcConfig:
      - enableInDozeMode: 'true'
      - conversionAverageMode: 'kLPADC_ConversionAverage1'
      - offsetCalibration: 'no'
      - autoCalibrate: 'false'
      - enableAnalogPreliminary: 'false'
      - powerUpDelay: '0x80'
      - referenceVoltageSource: 'kLPADC_ReferenceVoltageAlt2'
      - powerLevelMode: 'kLPADC_PowerLevelAlt1'
      - triggerPriorityPolicy: 'kLPADC_TriggerPriorityPreemptImmediately'
      - enableConvPause: 'false'
      - convPauseDelay: '0'
      - FIFO0Watermark: '0'
      - FIFO1Watermark: '0'
      - FIFO0WatermarkDMA: 'false'
      - FIFO1WatermarkDMA: 'false'
    - lpadcConvCommandConfig: []
    - lpadcConvTriggerConfig: []
    - IRQ_cfg:
      - interrupt_type: 'kLPADC_FIFO0WatermarkInterruptEnable'
      - enable_irq: 'true'
      - adc_interrupt:
        - IRQn: 'ADC0_IRQn'
        - enable_interrrupt: 'noInit'
        - enable_priority: 'false'
        - priority: '0'
        - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const lpadc_config_t ADC0_config = {
  .enableInDozeMode = true,
  .conversionAverageMode = kLPADC_ConversionAverage1,
  .enableAnalogPreliminary = false,
  .powerUpDelay = 0x80,
  .referenceVoltageSource = kLPADC_ReferenceVoltageAlt2,
  .powerLevelMode = kLPADC_PowerLevelAlt1,
  .triggerPriorityPolicy = kLPADC_TriggerPriorityPreemptImmediately,
  .enableConvPause = false,
  .convPauseDelay = 0,
  .FIFO0Watermark = 0,
  .FIFO1Watermark = 0
};

static void ADC0_init(void) {
  /* Initialize LPADC converter */
  LPADC_Init(ADC0_PERIPHERAL, &ADC0_config);
  /* Enable interrupts from LPADC */
  LPADC_EnableInterrupts(ADC0_PERIPHERAL, (kLPADC_FIFO0WatermarkInterruptEnable));
  /* Interrupt ADC0_IRQn request in the NVIC is not initialized (disabled by default). */
  /* It can be enabled later by EnableIRQ(ADC0_IRQn); function call. */
}

/***********************************************************************************************************************
 * CRC_ENGINE initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'CRC_ENGINE'
- type: 'lpc_crc'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'lpc_crc_5f5f079056dd2a843b86fbb64c18c8cd'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'CRC_ENGINE'
- config_sets:
  - fsl_crc:
    - crc_config:
      - polynomial: 'kCRC_Polynomial_CRC_32'
      - reverseIn: 'true'
      - complementIn: 'false'
      - reverseOut: 'true'
      - complementOut: 'true'
      - seed: '0xFFFFFFFF'
    - quick_selection: 'crc_32'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const crc_config_t CRC_ENGINE_config = {
  .polynomial = kCRC_Polynomial_CRC_32,
  .reverseIn = true,
  .complementIn = false,
  .reverseOut = true,
  .complementOut = true,
  .seed = 0xFFFFFFFF
};

static void CRC_ENGINE_init(void) {
  CRC_Init(CRC_ENGINE_PERIPHERAL, &CRC_ENGINE_config);
}

/***********************************************************************************************************************
 * CTIMER0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'CTIMER0'
- type: 'ctimer'
- mode: 'Capture_Match'
- custom_name_enabled: 'true'
- type_id: 'ctimer_c8b90232d8b6318ba1dac2cf08fb5f4a'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'CTIMER0'
- config_sets:
  - fsl_ctimer:
    - ctimerConfig:
      - mode: 'kCTIMER_TimerMode'
      - clockSource: 'FunctionClock'
      - clockSourceFreq: 'BOARD_BootClockRUN'
      - timerPrescaler: '1'
    - EnableTimerInInit: 'false'
    - matchChannels: []
    - interruptCallbackConfig:
      - interrupt:
        - IRQn: 'CTIMER0_IRQn'
        - enable_interrrupt: 'enabled'
        - enable_priority: 'false'
        - priority: '0'
      - callback: 'kCTIMER_NoCallback'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const ctimer_config_t CTIMER0_config = {
  .mode = kCTIMER_TimerMode,
  .input = kCTIMER_Capture_0,
  .prescale = 0
};

static void CTIMER0_init(void) {
  /* CTIMER0 peripheral initialization */
  CTIMER_Init(CTIMER0_PERIPHERAL, &CTIMER0_config);
}

/***********************************************************************************************************************
 * CTIMER1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'CTIMER1'
- type: 'ctimer'
- mode: 'Capture_Match'
- custom_name_enabled: 'false'
- type_id: 'ctimer_c8b90232d8b6318ba1dac2cf08fb5f4a'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'CTIMER1'
- config_sets:
  - fsl_ctimer:
    - ctimerConfig:
      - mode: 'kCTIMER_TimerMode'
      - clockSource: 'FunctionClock'
      - clockSourceFreq: 'BOARD_BootClockRUN'
      - timerPrescaler: '1'
    - EnableTimerInInit: 'false'
    - matchChannels: []
    - interruptCallbackConfig:
      - interrupt:
        - IRQn: 'CTIMER1_IRQn'
        - enable_interrrupt: 'enabled'
        - enable_priority: 'true'
        - priority: '0'
      - callback: 'kCTIMER_NoCallback'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const ctimer_config_t CTIMER1_config = {
  .mode = kCTIMER_TimerMode,
  .input = kCTIMER_Capture_0,
  .prescale = 0
};

static void CTIMER1_init(void) {
  /* CTIMER1 peripheral initialization */
  CTIMER_Init(CTIMER1_PERIPHERAL, &CTIMER1_config);
}

/***********************************************************************************************************************
 * CTIMER2 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'CTIMER2'
- type: 'ctimer'
- mode: 'Capture_Match'
- custom_name_enabled: 'false'
- type_id: 'ctimer_c8b90232d8b6318ba1dac2cf08fb5f4a'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'CTIMER2'
- config_sets:
  - fsl_ctimer:
    - ctimerConfig:
      - mode: 'kCTIMER_TimerMode'
      - clockSource: 'FunctionClock'
      - clockSourceFreq: 'BOARD_BootClockRUN'
      - timerPrescaler: '1'
    - EnableTimerInInit: 'false'
    - matchChannels: []
    - interruptCallbackConfig:
      - interrupt:
        - IRQn: 'CTIMER2_IRQn'
        - enable_interrrupt: 'enabled'
        - enable_priority: 'false'
        - priority: '0'
      - callback: 'kCTIMER_NoCallback'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const ctimer_config_t CTIMER2_config = {
  .mode = kCTIMER_TimerMode,
  .input = kCTIMER_Capture_0,
  .prescale = 0
};

static void CTIMER2_init(void) {
  /* CTIMER2 peripheral initialization */
  CTIMER_Init(CTIMER2_PERIPHERAL, &CTIMER2_config);
}

/***********************************************************************************************************************
 * CTIMER3 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'CTIMER3'
- type: 'ctimer'
- mode: 'Capture_Match'
- custom_name_enabled: 'false'
- type_id: 'ctimer_c8b90232d8b6318ba1dac2cf08fb5f4a'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'CTIMER3'
- config_sets:
  - fsl_ctimer:
    - ctimerConfig:
      - mode: 'kCTIMER_TimerMode'
      - clockSource: 'FunctionClock'
      - clockSourceFreq: 'BOARD_BootClockRUN'
      - timerPrescaler: '1'
    - EnableTimerInInit: 'false'
    - matchChannels: []
    - interruptCallbackConfig:
      - interrupt:
        - IRQn: 'CTIMER3_IRQn'
        - enable_interrrupt: 'enabled'
        - enable_priority: 'false'
        - priority: '0'
      - callback: 'kCTIMER_NoCallback'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const ctimer_config_t CTIMER3_config = {
  .mode = kCTIMER_TimerMode,
  .input = kCTIMER_Capture_0,
  .prescale = 0
};

static void CTIMER3_init(void) {
  /* CTIMER3 peripheral initialization */
  CTIMER_Init(CTIMER3_PERIPHERAL, &CTIMER3_config);
}

/***********************************************************************************************************************
 * CTIMER4 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'CTIMER4'
- type: 'ctimer'
- mode: 'Capture_Match'
- custom_name_enabled: 'false'
- type_id: 'ctimer_c8b90232d8b6318ba1dac2cf08fb5f4a'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'CTIMER4'
- config_sets:
  - fsl_ctimer:
    - ctimerConfig:
      - mode: 'kCTIMER_TimerMode'
      - clockSource: 'FunctionClock'
      - clockSourceFreq: 'BOARD_BootClockRUN'
      - timerPrescaler: '1'
    - EnableTimerInInit: 'false'
    - matchChannels: []
    - interruptCallbackConfig:
      - interrupt:
        - IRQn: 'CTIMER4_IRQn'
        - enable_interrrupt: 'enabled'
        - enable_priority: 'false'
        - priority: '0'
      - callback: 'kCTIMER_NoCallback'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const ctimer_config_t CTIMER4_config = {
  .mode = kCTIMER_TimerMode,
  .input = kCTIMER_Capture_0,
  .prescale = 0
};

static void CTIMER4_init(void) {
  /* CTIMER4 peripheral initialization */
  CTIMER_Init(CTIMER4_PERIPHERAL, &CTIMER4_config);
}

/***********************************************************************************************************************
 * I2C1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'I2C1'
- type: 'flexcomm_i2c'
- mode: 'I2C_Polling'
- custom_name_enabled: 'true'
- type_id: 'flexcomm_i2c_567d1a9d97c12e5d39b00259c3436dc4'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'FLEXCOMM1'
- config_sets:
  - fsl_i2c:
    - i2c_mode: 'kI2C_Master'
    - clockSource: 'FXCOMFunctionClock'
    - clockSourceFreq: 'BOARD_BootClockRUN'
    - i2c_master_config:
      - enableMaster: 'true'
      - baudRate_Bps: '100'
      - enableTimeout: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const i2c_master_config_t I2C1_config = {
  .enableMaster = true,
  .baudRate_Bps = 100,
  .enableTimeout = false
};

static void I2C1_init(void) {
  RESET_PeripheralReset( kFC1_RST_SHIFT_RSTn);
  /* Initialization function */
  I2C_MasterInit(I2C1_PERIPHERAL, &I2C1_config, I2C1_CLOCK_SOURCE);
}

/***********************************************************************************************************************
 * I2S7 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'I2S7'
- type: 'flexcomm_i2s'
- mode: 'dma'
- custom_name_enabled: 'true'
- type_id: 'flexcomm_i2s_d821d1d3dded76c4d4194ae52cbf73a5'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'FLEXCOMM7'
- config_sets:
  - fsl_i2s:
    - i2s_config:
      - usage: 'playback'
      - masterSlave: 'kI2S_MasterSlaveNormalMaster'
      - sckPolM: 'false'
      - wsPolM: 'false'
      - clockConfig:
        - sampleRate_Hz: 'kSAI_SampleRate44100Hz'
        - clockSource: 'FXCOMFunctionClock'
        - clockSourceFreq: 'BOARD_BootClockRUN'
        - masterClockDependency: 'true'
      - mode: 'kI2S_ModeI2sClassic'
      - dataLengthM: '16'
      - stereo: 'kSAI_Stereo'
      - i2s_mono_palcement: 'kSAI_Mono_Left'
      - positionM: '0'
      - frameLengthM: '32'
      - rightLow: 'false'
      - leftJust: 'false'
      - watermarkM_Tx: 'ki2s_TxFifo4'
      - txEmptyZeroTx: 'true'
      - pack48: 'false'
  - dmaCfg:
    - dma_channels:
      - dma_tx_channel:
        - DMA_source: 'kDma0RequestFlexcomm7Tx'
        - init_channel_priority: 'false'
        - dma_priority: 'kDMA_ChannelPriority0'
        - enable_custom_name: 'false'
    - i2s_dma_handle:
      - enable_custom_name: 'false'
      - init_callback: 'false'
      - callback_fcn: ''
      - user_data: ''
    - quick_selection: 'QuickSelection1'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
/* Flexcomm I2S configuration */
const i2s_config_t I2S7_config = {
  .masterSlave = kI2S_MasterSlaveNormalMaster,
  .mode = kI2S_ModeI2sClassic,
  .rightLow = false,
  .leftJust = false,
  .sckPol = false,
  .wsPol = false,
  .divider = 32,
  .oneChannel = false,
  .dataLength = 16,
  .frameLength = 32,
  .position = 0,
  .watermark = 4,
  .txEmptyZero = true,
  .pack48 = false
};
dma_handle_t I2S7_TX_Handle;
i2s_dma_handle_t I2S7_Tx_DMA_Handle;

static void I2S7_init(void) {
  RESET_PeripheralReset(kFC7_RST_SHIFT_RSTn);
  /* Flexcomm I2S initialization */
  I2S_TxInit(I2S7_PERIPHERAL, &I2S7_config);
  /* Enable the DMA 19channel in the DMA */
  DMA_EnableChannel(I2S7_TX_DMA_BASEADDR, I2S7_TX_DMA_CHANNEL);
  /* Create the DMA I2S7_TX_Handlehandle */
  DMA_CreateHandle(&I2S7_TX_Handle, I2S7_TX_DMA_BASEADDR, I2S7_TX_DMA_CHANNEL);
  /* Create the I2S DMA handle */
  I2S_TxTransferCreateHandleDMA(I2S7_PERIPHERAL, &I2S7_Tx_DMA_Handle, &I2S7_TX_Handle, NULL, NULL);
}

/***********************************************************************************************************************
 * RTC initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'RTC'
- type: 'lpc_rtc'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'lpc_rtc_607bd7331c2c81c0037fe4624be881b6'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'RTC'
- config_sets:
  - fsl_rtc:
    - rtc_config:
      - setDateTime: 'false'
      - setAlarmTime: 'false'
      - setWakeup: 'false'
      - alarm_wake_up_enable: 'false'
      - wake_up_enable: 'false'
      - start: 'false'
    - rtc_interrupt:
      - interrupt_vectors:
        - enable_irq: 'false'
        - interrupt:
          - IRQn: 'RTC_IRQn'
          - enable_interrrupt: 'enabled'
          - enable_priority: 'false'
          - priority: '0'
          - enable_custom_name: 'false'
    - quick_selection: 'QS_RTC_1'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

static void RTC_init(void) {
  /* RTC initialization */
  RTC_Init(RTC_PERIPHERAL);
}

/***********************************************************************************************************************
 * SPI0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'SPI0'
- type: 'flexcomm_spi'
- mode: 'SPI_Polling'
- custom_name_enabled: 'true'
- type_id: 'flexcomm_spi_481dadba00035f986f31ed9ac95af181'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'FLEXCOMM0'
- config_sets:
  - fsl_spi:
    - spi_mode: 'kSPI_Master'
    - clockSource: 'FXCOMFunctionClock'
    - clockSourceFreq: 'BOARD_BootClockRUN'
    - spi_master_config:
      - enableLoopback: 'false'
      - enableMaster: 'true'
      - polarity: 'kSPI_ClockPolarityActiveHigh'
      - phase: 'kSPI_ClockPhaseFirstEdge'
      - direction: 'kSPI_MsbFirst'
      - baudRate_Bps: '500000'
      - dataWidth: 'kSPI_Data8Bits'
      - sselNum: 'kSPI_Ssel0'
      - sselPol_set: ''
      - txWatermark: 'kSPI_TxFifo0'
      - rxWatermark: 'kSPI_RxFifo1'
      - delayConfig:
        - preDelay: '0'
        - postDelay: '0'
        - frameDelay: '0'
        - transferDelay: '0'
    - quick_selection: 'QS_SPI_1'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const spi_master_config_t SPI0_config = {
  .enableLoopback = false,
  .enableMaster = true,
  .polarity = kSPI_ClockPolarityActiveHigh,
  .phase = kSPI_ClockPhaseFirstEdge,
  .direction = kSPI_MsbFirst,
  .baudRate_Bps = 500000,
  .dataWidth = kSPI_Data8Bits,
  .sselNum = kSPI_Ssel0,
  .sselPol = kSPI_SpolActiveAllLow,
  .txWatermark = kSPI_TxFifo0,
  .rxWatermark = kSPI_RxFifo1,
  .delayConfig = {
    .preDelay = 0,
    .postDelay = 0,
    .frameDelay = 0,
    .transferDelay = 0
  }
};

static void SPI0_init(void) {
  RESET_PeripheralReset(kFC0_RST_SHIFT_RSTn);
  /* Initialization function */
  SPI_MasterInit(SPI0_PERIPHERAL, &SPI0_config, SPI0_CLOCK_SOURCE);
}

/***********************************************************************************************************************
 * SPI3 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'SPI3'
- type: 'flexcomm_spi'
- mode: 'SPI_Polling'
- custom_name_enabled: 'true'
- type_id: 'flexcomm_spi_481dadba00035f986f31ed9ac95af181'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'FLEXCOMM3'
- config_sets:
  - fsl_spi:
    - spi_mode: 'kSPI_Master'
    - clockSource: 'FXCOMFunctionClock'
    - clockSourceFreq: 'BOARD_BootClockRUN'
    - spi_master_config:
      - enableLoopback: 'false'
      - enableMaster: 'true'
      - polarity: 'kSPI_ClockPolarityActiveHigh'
      - phase: 'kSPI_ClockPhaseFirstEdge'
      - direction: 'kSPI_MsbFirst'
      - baudRate_Bps: '5000000'
      - dataWidth: 'kSPI_Data8Bits'
      - sselNum: 'kSPI_Ssel0'
      - sselPol_set: ''
      - txWatermark: 'kSPI_TxFifo0'
      - rxWatermark: 'kSPI_RxFifo1'
      - delayConfig:
        - preDelay: '0'
        - postDelay: '0'
        - frameDelay: '0'
        - transferDelay: '0'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const spi_master_config_t SPI3_config = {
  .enableLoopback = false,
  .enableMaster = true,
  .polarity = kSPI_ClockPolarityActiveHigh,
  .phase = kSPI_ClockPhaseFirstEdge,
  .direction = kSPI_MsbFirst,
  .baudRate_Bps = 5000000,
  .dataWidth = kSPI_Data8Bits,
  .sselNum = kSPI_Ssel0,
  .sselPol = kSPI_SpolActiveAllLow,
  .txWatermark = kSPI_TxFifo0,
  .rxWatermark = kSPI_RxFifo1,
  .delayConfig = {
    .preDelay = 0,
    .postDelay = 0,
    .frameDelay = 0,
    .transferDelay = 0
  }
};

static void SPI3_init(void) {
  RESET_PeripheralReset(kFC3_RST_SHIFT_RSTn);
  /* Initialization function */
  SPI_MasterInit(SPI3_PERIPHERAL, &SPI3_config, SPI3_CLOCK_SOURCE);
}

/***********************************************************************************************************************
 * SPI6 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'SPI6'
- type: 'flexcomm_spi'
- mode: 'SPI_Polling'
- custom_name_enabled: 'true'
- type_id: 'flexcomm_spi_481dadba00035f986f31ed9ac95af181'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'FLEXCOMM6'
- config_sets:
  - fsl_spi:
    - spi_mode: 'kSPI_Master'
    - clockSource: 'FXCOMFunctionClock'
    - clockSourceFreq: 'BOARD_BootClockRUN'
    - spi_master_config:
      - enableLoopback: 'false'
      - enableMaster: 'true'
      - polarity: 'kSPI_ClockPolarityActiveLow'
      - phase: 'kSPI_ClockPhaseSecondEdge'
      - direction: 'kSPI_MsbFirst'
      - baudRate_Bps: '1000000'
      - dataWidth: 'kSPI_Data8Bits'
      - sselNum: 'kSPI_Ssel0'
      - sselPol_set: ''
      - txWatermark: 'kSPI_TxFifo0'
      - rxWatermark: 'kSPI_RxFifo1'
      - delayConfig:
        - preDelay: '0'
        - postDelay: '0'
        - frameDelay: '0'
        - transferDelay: '0'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const spi_master_config_t SPI6_config = {
  .enableLoopback = false,
  .enableMaster = true,
  .polarity = kSPI_ClockPolarityActiveLow,
  .phase = kSPI_ClockPhaseSecondEdge,
  .direction = kSPI_MsbFirst,
  .baudRate_Bps = 1000000,
  .dataWidth = kSPI_Data8Bits,
  .sselNum = kSPI_Ssel0,
  .sselPol = kSPI_SpolActiveAllLow,
  .txWatermark = kSPI_TxFifo0,
  .rxWatermark = kSPI_RxFifo1,
  .delayConfig = {
    .preDelay = 0,
    .postDelay = 0,
    .frameDelay = 0,
    .transferDelay = 0
  }
};

static void SPI6_init(void) {
  RESET_PeripheralReset(kFC6_RST_SHIFT_RSTn);
  /* Initialization function */
  SPI_MasterInit(SPI6_PERIPHERAL, &SPI6_config, SPI6_CLOCK_SOURCE);
}

/***********************************************************************************************************************
 * SPI8 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'SPI8'
- type: 'flexcomm_spi'
- mode: 'SPI_Polling'
- custom_name_enabled: 'true'
- type_id: 'flexcomm_spi_481dadba00035f986f31ed9ac95af181'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'FLEXCOMM8'
- config_sets:
  - fsl_spi:
    - spi_mode: 'kSPI_Master'
    - clockSource: 'FXCOMFunctionClock'
    - clockSourceFreq: 'BOARD_BootClockRUN'
    - spi_master_config:
      - enableLoopback: 'false'
      - enableMaster: 'true'
      - polarity: 'kSPI_ClockPolarityActiveHigh'
      - phase: 'kSPI_ClockPhaseFirstEdge'
      - direction: 'kSPI_MsbFirst'
      - baudRate_Bps: '1000000'
      - dataWidth: 'kSPI_Data8Bits'
      - sselNum: 'kSPI_Ssel0'
      - sselPol_set: ''
      - txWatermark: 'kSPI_TxFifo0'
      - rxWatermark: 'kSPI_RxFifo1'
      - delayConfig:
        - preDelay: '0'
        - postDelay: '0'
        - frameDelay: '0'
        - transferDelay: '0'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const spi_master_config_t SPI8_config = {
  .enableLoopback = false,
  .enableMaster = true,
  .polarity = kSPI_ClockPolarityActiveHigh,
  .phase = kSPI_ClockPhaseFirstEdge,
  .direction = kSPI_MsbFirst,
  .baudRate_Bps = 1000000,
  .dataWidth = kSPI_Data8Bits,
  .sselNum = kSPI_Ssel0,
  .sselPol = kSPI_SpolActiveAllLow,
  .txWatermark = kSPI_TxFifo0,
  .rxWatermark = kSPI_RxFifo1,
  .delayConfig = {
    .preDelay = 0,
    .postDelay = 0,
    .frameDelay = 0,
    .transferDelay = 0
  }
};

static void SPI8_init(void) {
  RESET_PeripheralReset(kHSLSPI_RST_SHIFT_RSTn);
  /* Initialization function */
  SPI_MasterInit(SPI8_PERIPHERAL, &SPI8_config, SPI8_CLOCK_SOURCE);
}

/***********************************************************************************************************************
 * USART2 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'USART2'
- type: 'flexcomm_usart'
- mode: 'dma'
- custom_name_enabled: 'true'
- type_id: 'flexcomm_usart_1a3fb4b775feaf430dd3789553461e5c'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'FLEXCOMM2'
- config_sets:
  - dmaCfg:
    - dma_channels:
      - enable_rx_dma_channel: 'true'
      - dma_rx_channel:
        - DMA_source: 'kDma0RequestFlexcomm2Rx'
        - init_channel_priority: 'false'
        - dma_priority: 'kDMA_ChannelPriority0'
        - enable_custom_name: 'false'
      - enable_tx_dma_channel: 'true'
      - dma_tx_channel:
        - DMA_source: 'kDma0RequestFlexcomm2Tx'
        - init_channel_priority: 'false'
        - dma_priority: 'kDMA_ChannelPriority0'
        - enable_custom_name: 'false'
    - usart_dma_handle:
      - enable_custom_name: 'false'
      - init_callback: 'false'
      - callback_fcn: ''
      - user_data: ''
  - usartConfig_t:
    - usartConfig:
      - clockSource: 'FXCOMFunctionClock'
      - clockSourceFreq: 'BOARD_BootClockRUN'
      - baudRate_Bps: '115200'
      - syncMode: 'kUSART_SyncModeDisabled'
      - parityMode: 'kUSART_ParityDisabled'
      - stopBitCount: 'kUSART_OneStopBit'
      - bitCountPerChar: 'kUSART_8BitsPerChar'
      - loopback: 'false'
      - txWatermark: 'kUSART_TxFifo0'
      - rxWatermark: 'kUSART_RxFifo1'
      - enableRx: 'true'
      - enableTx: 'true'
      - clockPolarity: 'kUSART_RxSampleOnFallingEdge'
      - enableContinuousSCLK: 'false'
    - quick_selection: 'QuickSelection1'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const usart_config_t USART2_config = {
  .baudRate_Bps = 115200,
  .syncMode = kUSART_SyncModeDisabled,
  .parityMode = kUSART_ParityDisabled,
  .stopBitCount = kUSART_OneStopBit,
  .bitCountPerChar = kUSART_8BitsPerChar,
  .loopback = false,
  .txWatermark = kUSART_TxFifo0,
  .rxWatermark = kUSART_RxFifo1,
  .enableRx = true,
  .enableTx = true,
  .enableMode32k = false,
  .clockPolarity = kUSART_RxSampleOnFallingEdge,
  .enableContinuousSCLK = false
};
dma_handle_t USART2_RX_Handle;
dma_handle_t USART2_TX_Handle;
usart_dma_handle_t USART2_USART_DMA_Handle;

static void USART2_init(void) {
  /* Reset FLEXCOMM device */
  RESET_PeripheralReset(kFC2_RST_SHIFT_RSTn);
  USART_Init(USART2_PERIPHERAL, &USART2_config, USART2_CLOCK_SOURCE);
  /* Enable the DMA 10channel in the DMA */
  DMA_EnableChannel(USART2_RX_DMA_BASEADDR, USART2_RX_DMA_CHANNEL);
  /* Create the DMA USART2_RX_Handlehandle */
  DMA_CreateHandle(&USART2_RX_Handle, USART2_RX_DMA_BASEADDR, USART2_RX_DMA_CHANNEL);
  /* Enable the DMA 11channel in the DMA */
  DMA_EnableChannel(USART2_TX_DMA_BASEADDR, USART2_TX_DMA_CHANNEL);
  /* Create the DMA USART2_TX_Handlehandle */
  DMA_CreateHandle(&USART2_TX_Handle, USART2_TX_DMA_BASEADDR, USART2_TX_DMA_CHANNEL);
  /* Create the USART DMA handle */
  USART_TransferCreateHandleDMA(USART2_PERIPHERAL, &USART2_USART_DMA_Handle, NULL, NULL, &USART2_TX_Handle, &USART2_RX_Handle);
}

/***********************************************************************************************************************
 * USART4 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'USART4'
- type: 'flexcomm_usart'
- mode: 'dma'
- custom_name_enabled: 'true'
- type_id: 'flexcomm_usart_1a3fb4b775feaf430dd3789553461e5c'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'FLEXCOMM4'
- config_sets:
  - dmaCfg:
    - dma_channels:
      - enable_rx_dma_channel: 'true'
      - dma_rx_channel:
        - DMA_source: 'kDma0RequestFlexcomm4Rx'
        - init_channel_priority: 'false'
        - dma_priority: 'kDMA_ChannelPriority0'
        - enable_custom_name: 'false'
      - enable_tx_dma_channel: 'true'
      - dma_tx_channel:
        - DMA_source: 'kDma0RequestFlexcomm4Tx'
        - init_channel_priority: 'false'
        - dma_priority: 'kDMA_ChannelPriority0'
        - enable_custom_name: 'false'
    - usart_dma_handle:
      - enable_custom_name: 'false'
      - init_callback: 'false'
      - callback_fcn: ''
      - user_data: ''
    - quick_selection: 'QuickSelection1'
  - usartConfig_t:
    - usartConfig:
      - clockSource: 'FXCOMFunctionClock'
      - clockSourceFreq: 'BOARD_BootClockRUN'
      - baudRate_Bps: '115200'
      - syncMode: 'kUSART_SyncModeDisabled'
      - parityMode: 'kUSART_ParityDisabled'
      - stopBitCount: 'kUSART_OneStopBit'
      - bitCountPerChar: 'kUSART_8BitsPerChar'
      - loopback: 'false'
      - txWatermark: 'kUSART_TxFifo0'
      - rxWatermark: 'kUSART_RxFifo1'
      - enableRx: 'true'
      - enableTx: 'true'
      - clockPolarity: 'kUSART_RxSampleOnFallingEdge'
      - enableContinuousSCLK: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const usart_config_t USART4_config = {
  .baudRate_Bps = 115200,
  .syncMode = kUSART_SyncModeDisabled,
  .parityMode = kUSART_ParityDisabled,
  .stopBitCount = kUSART_OneStopBit,
  .bitCountPerChar = kUSART_8BitsPerChar,
  .loopback = false,
  .txWatermark = kUSART_TxFifo0,
  .rxWatermark = kUSART_RxFifo1,
  .enableRx = true,
  .enableTx = true,
  .enableMode32k = false,
  .clockPolarity = kUSART_RxSampleOnFallingEdge,
  .enableContinuousSCLK = false
};
dma_handle_t USART4_RX_Handle;
dma_handle_t USART4_TX_Handle;
usart_dma_handle_t USART4_USART_DMA_Handle;

static void USART4_init(void) {
  /* Reset FLEXCOMM device */
  RESET_PeripheralReset(kFC4_RST_SHIFT_RSTn);
  USART_Init(USART4_PERIPHERAL, &USART4_config, USART4_CLOCK_SOURCE);
  /* Enable the DMA 12channel in the DMA */
  DMA_EnableChannel(USART4_RX_DMA_BASEADDR, USART4_RX_DMA_CHANNEL);
  /* Create the DMA USART4_RX_Handlehandle */
  DMA_CreateHandle(&USART4_RX_Handle, USART4_RX_DMA_BASEADDR, USART4_RX_DMA_CHANNEL);
  /* Enable the DMA 13channel in the DMA */
  DMA_EnableChannel(USART4_TX_DMA_BASEADDR, USART4_TX_DMA_CHANNEL);
  /* Create the DMA USART4_TX_Handlehandle */
  DMA_CreateHandle(&USART4_TX_Handle, USART4_TX_DMA_BASEADDR, USART4_TX_DMA_CHANNEL);
  /* Create the USART DMA handle */
  USART_TransferCreateHandleDMA(USART4_PERIPHERAL, &USART4_USART_DMA_Handle, NULL, NULL, &USART4_TX_Handle, &USART4_RX_Handle);
}

/***********************************************************************************************************************
 * USART5 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'USART5'
- type: 'flexcomm_usart'
- mode: 'dma'
- custom_name_enabled: 'true'
- type_id: 'flexcomm_usart_1a3fb4b775feaf430dd3789553461e5c'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'FLEXCOMM5'
- config_sets:
  - dmaCfg:
    - dma_channels:
      - enable_rx_dma_channel: 'true'
      - dma_rx_channel:
        - DMA_source: 'kDma0RequestFlexcomm5Rx'
        - init_channel_priority: 'false'
        - dma_priority: 'kDMA_ChannelPriority0'
        - enable_custom_name: 'false'
      - enable_tx_dma_channel: 'true'
      - dma_tx_channel:
        - DMA_source: 'kDma0RequestFlexcomm5Tx'
        - init_channel_priority: 'false'
        - dma_priority: 'kDMA_ChannelPriority0'
        - enable_custom_name: 'false'
    - usart_dma_handle:
      - enable_custom_name: 'false'
      - init_callback: 'false'
      - callback_fcn: ''
      - user_data: ''
    - quick_selection: 'QuickSelection1'
  - usartConfig_t:
    - usartConfig:
      - clockSource: 'FXCOMFunctionClock'
      - clockSourceFreq: 'BOARD_BootClockRUN'
      - baudRate_Bps: '115200'
      - syncMode: 'kUSART_SyncModeDisabled'
      - parityMode: 'kUSART_ParityDisabled'
      - stopBitCount: 'kUSART_OneStopBit'
      - bitCountPerChar: 'kUSART_8BitsPerChar'
      - loopback: 'false'
      - txWatermark: 'kUSART_TxFifo0'
      - rxWatermark: 'kUSART_RxFifo1'
      - enableRx: 'true'
      - enableTx: 'true'
      - clockPolarity: 'kUSART_RxSampleOnFallingEdge'
      - enableContinuousSCLK: 'false'
    - quick_selection: 'QuickSelection1'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const usart_config_t USART5_config = {
  .baudRate_Bps = 115200,
  .syncMode = kUSART_SyncModeDisabled,
  .parityMode = kUSART_ParityDisabled,
  .stopBitCount = kUSART_OneStopBit,
  .bitCountPerChar = kUSART_8BitsPerChar,
  .loopback = false,
  .txWatermark = kUSART_TxFifo0,
  .rxWatermark = kUSART_RxFifo1,
  .enableRx = true,
  .enableTx = true,
  .enableMode32k = false,
  .clockPolarity = kUSART_RxSampleOnFallingEdge,
  .enableContinuousSCLK = false
};
dma_handle_t USART5_RX_Handle;
dma_handle_t USART5_TX_Handle;
usart_dma_handle_t USART5_USART_DMA_Handle;

static void USART5_init(void) {
  /* Reset FLEXCOMM device */
  RESET_PeripheralReset(kFC5_RST_SHIFT_RSTn);
  USART_Init(USART5_PERIPHERAL, &USART5_config, USART5_CLOCK_SOURCE);
  /* Enable the DMA 14channel in the DMA */
  DMA_EnableChannel(USART5_RX_DMA_BASEADDR, USART5_RX_DMA_CHANNEL);
  /* Create the DMA USART5_RX_Handlehandle */
  DMA_CreateHandle(&USART5_RX_Handle, USART5_RX_DMA_BASEADDR, USART5_RX_DMA_CHANNEL);
  /* Enable the DMA 15channel in the DMA */
  DMA_EnableChannel(USART5_TX_DMA_BASEADDR, USART5_TX_DMA_CHANNEL);
  /* Create the DMA USART5_TX_Handlehandle */
  DMA_CreateHandle(&USART5_TX_Handle, USART5_TX_DMA_BASEADDR, USART5_TX_DMA_CHANNEL);
  /* Create the USART DMA handle */
  USART_TransferCreateHandleDMA(USART5_PERIPHERAL, &USART5_USART_DMA_Handle, NULL, NULL, &USART5_TX_Handle, &USART5_RX_Handle);
}

/***********************************************************************************************************************
 * USB0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'USB0'
- type: 'usb'
- mode: 'device'
- custom_name_enabled: 'false'
- type_id: 'usb_c84d398fe7344af73d7dbb640d3b1867'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'USB0'
- config_sets:
  - deviceSetting:
    - vendor_id: '0x1FC9'
    - product_id: '0x0091'
    - manufacturer_string: 'NXP'
    - product_string: 'Mouse'
    - self_powered: 'false'
    - max_power: '100'
    - interfaces:
      - 0:
        - interface_class: 'kClassHid'
        - setting_hid:
          - interface_name: 'HID Mouse'
          - implementation: 'kImplementationMouse'
          - subclass: 'kSubclassBootInterface'
          - protocol: 'kProtocolMouse'
          - endpoints_settings:
            - 0:
              - setting_name: 'Default'
              - endpoints:
                - 0:
                  - direction: 'kIn'
                  - transfer_type: 'kInterrupt'
                  - synchronization: 'kNoSynchronization'
                  - usage: 'kData'
                  - max_packet_size_fs: 'k8'
                  - polling_interval_fs: '4'
                  - bRefresh: '0'
                  - bSynchAddress: 'NoSynchronization'
          - report_descriptor:
            - 0:
              - type: 'kUsage_Page'
              - value: '0x01'
              - remarks: 'Usage Page (Generic Desktop)'
            - 1:
              - type: 'kUsage'
              - value: '0x02'
              - remarks: 'Usage (Mouse)'
            - 2:
              - type: 'kCollection'
              - value: '0x01'
              - remarks: 'Collection (Application)'
            - 3:
              - type: 'kUsage'
              - value: '0x01'
              - remarks: 'Usage (Pointer)'
            - 4:
              - type: 'kCollection'
              - value: '0x00'
              - remarks: 'Collection (Physical)'
            - 5:
              - type: 'kUsage_Page'
              - value: '0x09'
              - remarks: 'Usage Page (Buttons)'
            - 6:
              - type: 'kUsage_Minimum'
              - value: '0x01'
              - remarks: 'Usage Minimum (01U)'
            - 7:
              - type: 'kUsage_Maximum'
              - value: '0x07'
              - remarks: 'Usage Maximum (07U)'
            - 8:
              - type: 'kLogical_Minimum'
              - value: '0x00'
              - remarks: 'Logical Minimum'
            - 9:
              - type: 'kLogical_Maximum'
              - value: '0x01'
              - remarks: 'Logical Maximum (1U)'
            - 10:
              - type: 'kReport_Count'
              - value: '0x03'
              - remarks: 'Report Count (3U)'
            - 11:
              - type: 'kReport_Size'
              - value: '0x01'
              - remarks: 'Report Size (1U)'
            - 12:
              - type: 'kInput'
              - value: '0x02'
              - remarks: 'Input(Data, Variable, Absolute) 3U button bit fields'
            - 13:
              - type: 'kReport_Count'
              - value: '0x01'
              - remarks: 'Report Count (1U)'
            - 14:
              - type: 'kReport_Size'
              - value: '0x05'
              - remarks: 'Report Size (5U)'
            - 15:
              - type: 'kInput'
              - value: '0x01'
              - remarks: 'Input (Constant), 5U constant field'
            - 16:
              - type: 'kUsage_Page'
              - value: '0x01'
              - remarks: 'Usage Page (Generic Desktop)'
            - 17:
              - type: 'kUsage'
              - value: '0x30'
              - remarks: 'Usage (X)'
            - 18:
              - type: 'kUsage'
              - value: '0x31'
              - remarks: 'Usage (Y)'
            - 19:
              - type: 'kUsage'
              - value: '0x38'
              - remarks: 'Usage (Z)'
            - 20:
              - type: 'kLogical_Minimum'
              - value: '-127'
              - remarks: 'Logical Minimum (-127)'
            - 21:
              - type: 'kLogical_Maximum'
              - value: '0x7F'
              - remarks: 'Logical Maximum (127)'
            - 22:
              - type: 'kReport_Size'
              - value: '0x08'
              - remarks: 'Report Size (8U)'
            - 23:
              - type: 'kReport_Count'
              - value: '0x03'
              - remarks: 'Report Count (3U)'
            - 24:
              - type: 'kInput'
              - value: '0x06'
              - remarks: 'Input(Data, Variable, Relative), Three position bytes (X, Y, Z)'
            - 25:
              - type: 'kEnd_Collection'
              - remarks: 'End collection, Close Pointer collection'
            - 26:
              - type: 'kEnd_Collection'
              - remarks: 'End collection, Close Mouse collection'
          - quick_selection: 'QS_INTERFACE_HID_MOUSE'
    - quick_selection: 'QS_DEVICE_HID_MOUSE'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

static void USB0_init(void) {
  USB_DeviceApplicationInit();
}

/***********************************************************************************************************************
 * UTICK0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'UTICK0'
- type: 'utick'
- mode: 'general_config'
- custom_name_enabled: 'false'
- type_id: 'utick_58a3a3f691b03a130cd9419552f8327d'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'UTICK0'
- config_sets:
  - fsl_utick:
    - clockSettingUTICK:
      - clockSource: 'FunctionClock'
      - clockSourceFreq: 'BOARD_BootClockRUN'
    - timerSettingUTICK:
      - utick_mode_t: 'kUTICK_Repeat'
      - startTimer: 'false'
      - timerValueStr: ''
      - callbackEnable: 'false'
    - interrupt:
      - IRQn: 'UTICK0_IRQn'
      - enable_interrrupt: 'noInit'
      - enable_priority: 'false'
      - priority: '0'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

static void UTICK0_init(void) {
  /* UTICK0 peripheral initialization */
  UTICK_Init(UTICK0_PERIPHERAL);
  /* Configuration of UTICK0 peripheral initialization */
  UTICK_SetTick(UTICK0_PERIPHERAL, UTICK0_MODE, UTICK0_TICKS, NULL);
}

/***********************************************************************************************************************
 * WWDT initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'WWDT'
- type: 'wwdt'
- mode: 'reset_mode'
- custom_name_enabled: 'false'
- type_id: 'wwdt_4afd1b7f7bc88fc51c044e9c38c1808c'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'WWDT'
- config_sets:
  - general:
    - wwdt_config:
      - clockSource: 'FunctionClock'
      - clockSourceFreq: 'BOARD_BootClockRUN'
      - enableWwdt: 'false'
      - enableWatchdogProtect: 'false'
      - timeoutValue_input: '0x2FFF'
      - windowEnable: 'false'
      - warningValue_input: '0'
    - interrupt:
      - IRQn: 'WDT_BOD_IRQn'
      - enable_interrrupt: 'noInit'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const wwdt_config_t WWDT_config = {
  .enableWwdt = false,
  .enableWatchdogReset = true,
  .enableWatchdogProtect = false,
  .windowValue = WWDT_WINDOW,
  .timeoutValue = WWDT_TIMEOUT,
  .warningValue = WWDT_WARNING,
  .clockFreq_Hz = 3906
};

static void WWDT_init(void) {
  /* WWDT initiation  */
  WWDT_Init(WWDT_PERIPHERAL, &WWDT_config);
  /* Interrupt WDT_BOD_IRQn request in the NVIC is not initialized (disabled by default). */
  /* It can be enabled later by EnableIRQ(WWDT_IRQN);  function call. */
}

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
void BOARD_InitPeripherals(void)
{
  /* Global initialization */
  DMA_Init(DMA0_DMA_BASEADDR);

  /* Initialize components */
  DMA0_init();
  ADC0_init();
  CRC_ENGINE_init();
  CTIMER0_init();
  CTIMER1_init();
  CTIMER2_init();
  CTIMER3_init();
  CTIMER4_init();
  I2C1_init();
  I2S7_init();
  RTC_init();
  SPI0_init();
  SPI3_init();
  SPI6_init();
  SPI8_init();
  USART2_init();
  USART4_init();
  USART5_init();
  USB0_init();
  UTICK0_init();
  WWDT_init();
}

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void)
{
  BOARD_InitPeripherals();
}
