Import('OS_ROOT')
Import('osconfig')
from build_tools import *

# get current directory
pwd = PresentDir()

# The set of source files associated with this SConscript file.
src = Split("""
drv_common.c
""")

if IsDefined(['BSP_USING_GPIO', 'OS_USING_PIN']):
    src += ['drv_gpio.c']
    
if IsDefined(['BSP_USING_UART', 'OS_USING_SERIAL']):
    src += ['drv_usart.c']
    
if IsDefined(['BSP_USING_ONCHIP_RTC', 'OS_USING_RTC']):
    src += ['drv_rtc.c']

if IsDefined(['BSP_USING_WDG', 'OS_USING_WDG']):
    src += ['drv_wdg.c']
    
if IsDefined(['BSP_USING_PWM', 'OS_USING_PWM']):
    src += ['drv_pwm.c']

if IsDefined(['BSP_USING_ADC', 'OS_USING_ADC']):
    src += ['drv_adc.c']
    
if IsDefined(['BSP_USING_TIM', 'OS_USING_TIMER_DRIVER']):
    src += ['drv_gpt.c']

if IsDefined(['BSP_USING_SPI', 'OS_USING_SPI']):
    src += ['drv_spi.c']

if IsDefined(['OS_USING_LPMGR']):
    src += ['drv_lpmgr.c']

path = [pwd]

group = AddCodeGroup('cm_drivers', src, depend = ['SOC_FAMILY_MT2625'], CPPPATH = path)

Return('group')
