Import('OS_ROOT')
Import('osconfig')
from build_tools import *

pwd = PresentDir()

src = ['esp32_devices.c']

path =  [pwd]

group = AddCodeGroup('hal/devices', src, depend = ['SOC_FAMILY_ESP32'], CPPPATH = path)

Return('group')
