Import('osconfig')
from build_tools import *

pwd  = PresentDir()
src  = []
group = []
path = [pwd]


src += Glob('*.c')
src += Glob('*_gcc.S')  


group = AddCodeGroup('cpu', src, depend = ['ARCH_RISCV'], CPPPATH = path)

Return('group')
