import osconfig
from build_tools import *

pwd     = PresentDir()
src     = []
CPPPATH = []

LIB		= []
LIBPATH = []
group 	= []

if IsDefined('OS_USING_OnePos'):
	CPPPATH = [pwd + '/include']

	if IsDefined('ONEPOS_CMD'):
		src += Glob('source/onepos_cmd.c')
	
	if IsDefined('ONEPOS_WIFI_POS'):
		src += Glob('source/wifi_src/*.c')
		
	if IsDefined('ONEPOS_CELL_POS'):
		src += Glob('source/cell_src/*.c')
	
	if IsDefined('ONEPOS_WIFI_POS') or IsDefined('ONEPOS_CELL_POS'):
		src += Glob('source/onepos_src_info.c')
		src += Glob('source/onepos_interface.c')

	if IsDefined('ONEPOS_GNSS_POS'):
		src += Glob('source/gnss_src/*.c')
	
group = AddCodeGroup('onepos', src, depend = ['OS_USING_OnePos'], CPPPATH = CPPPATH)

Return('group')
