Import('OS_ROOT')
from build_tools import *

group = []

if IsDefined('MQTT_USING_SAMPLE'):
    src = Glob('*.c')
else:
    Return('group')
    
# The set of source files associated with this SConscript file.
path = [PresentDir() ]

group = AddCodeGroup('pahomqtt', src, depend = ['NET_USING_PAHO_MQTT'], CPPPATH = path)

Return('group')
