Import('OS_ROOT')
Import('osconfig')
from build_tools import *

pwd = PresentDir()
path =  [pwd]

src = Glob('*.c')

group = AddCodeGroup('application', src, depend = [''], CPPPATH = path)

Return('group')
