Import('OS_ROOT')
from build_tools import *

# get current directory
pwd = PresentDir()
src = []

path = [pwd,
		pwd + '/dm_utils',
		pwd + '/er-coap-13',
		pwd + '/std_object']

if IsDefined('OS_USING_ONENET_NBIOT'):
    src  = Glob('*.c')
    src += Glob('dm_utils/*.c')
    src += Glob('er-coap-13/*.c')
    src += Glob('std_object/*.c')

group = AddCodeGroup('onenet', src, depend = ['OS_USING_ONENET_NBIOT'], CPPPATH = path)

Return('group')
