# for module compiling
import os
from build_tools import *

objs = []
pwd  = PresentDir()
ver_path=""

if IsDefined(['SECURITY_USING_MBEDTLS_V2710']):
    ver_path = "mbedtls-v2.7.10"

    if os.path.isfile(os.path.join(pwd, ver_path, 'SConscript')):
        objs = objs + SConscript(os.path.join(ver_path, 'SConscript'))

Return('objs')
