/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v8.0
processor: MIMXRT1052xxxxB
package_id: MIMXRT1052DVL6B
mcu_data: ksdk2_0
processor_version: 8.0.2
board: IMXRT1050-EVKB
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: 3067509f-e55d-4865-8da6-e431102009b8
  called_from_default_init: true
  selectedCore: core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'system'
- type_id: 'system_54b53072540eeeb8f8e9343e71f28176'
- global_system_definitions:
  - user_definitions: ''
  - user_includes: ''
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "peripherals.h"

/***********************************************************************************************************************
 * BOARD_InitPeripherals functional group
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * DMA0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'DMA0'
- type: 'edma'
- mode: 'basic'
- custom_name_enabled: 'false'
- type_id: 'edma_6d0dd4e17e2f179c7d42d98767129ede'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'DMA0'
- config_sets:
  - fsl_edma:
    - common_settings:
      - enableContinuousLinkMode: 'false'
      - enableHaltOnError: 'true'
      - enableRoundRobinArbitration: 'false'
      - enableDebugMode: 'false'
    - dma_table:
      - 0: []
      - 1: []
    - edma_channels: []
    - errInterruptConfig:
      - enableErrInterrupt: 'false'
      - errorInterrupt:
        - IRQn: 'DMA_ERROR_IRQn'
        - enable_interrrupt: 'enabled'
        - enable_priority: 'false'
        - priority: '0'
        - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const edma_config_t DMA0_config = {
  .enableContinuousLinkMode = false,
  .enableHaltOnError = true,
  .enableRoundRobinArbitration = false,
  .enableDebugMode = false
};

static void DMA0_init(void) {
}

/***********************************************************************************************************************
 * ADC1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'ADC1'
- type: 'adc_12b1msps_sar'
- mode: 'ADC_GENERAL'
- custom_name_enabled: 'false'
- type_id: 'adc_12b1msps_sar_6a490e886349a7b2b07bed10ce7b299b'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'ADC1'
- config_sets:
  - fsl_adc:
    - clockConfig:
      - clockSource: 'kADC_ClockSourceAD'
      - clockSourceFreq: 'custom:10 MHz'
      - clockDriver: 'kADC_ClockDriver1'
      - samplePeriodMode: 'kADC_SamplePeriodLong12Clcoks'
      - enableAsynchronousClockOutput: 'true'
    - conversionConfig:
      - resolution: 'kADC_Resolution12Bit'
      - hardwareAverageMode: 'kADC_HardwareAverageDisable'
      - enableHardwareTrigger: 'software'
      - enableHighSpeed: 'false'
      - enableLowPower: 'false'
      - enableContinuousConversion: 'false'
      - enableOverWrite: 'false'
      - enableDma: 'false'
    - resultingTime: []
    - resultCorrection:
      - doAutoCalibration: 'false'
      - offset: '0'
    - hardwareCompareConfiguration:
      - hardwareCompareMode: 'disabled'
      - value1: '0'
      - value2: '0'
    - enableInterrupt: 'false'
    - adc_interrupt:
      - IRQn: 'ADC1_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - adc_channels_config: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const adc_config_t ADC1_config = {
  .enableOverWrite = false,
  .enableContinuousConversion = false,
  .enableHighSpeed = false,
  .enableLowPower = false,
  .enableLongSample = true,
  .enableAsynchronousClockOutput = true,
  .referenceVoltageSource = kADC_ReferenceVoltageSourceAlt0,
  .samplePeriodMode = kADC_SamplePeriodLong12Clcoks,
  .clockSource = kADC_ClockSourceAD,
  .clockDriver = kADC_ClockDriver1,
  .resolution = kADC_Resolution12Bit
};

static void ADC1_init(void) {
  /* Initialize ADC1 peripheral. */
  ADC_Init(ADC1_PERIPHERAL, &ADC1_config);
}

/***********************************************************************************************************************
 * ADC_ETC initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'ADC_ETC'
- type: 'adc_etc'
- mode: 'ADC_ETC_SW'
- custom_name_enabled: 'false'
- type_id: 'adc_etc_05e3d3ed2376fa5bde10b24efc9ee456'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'ADC_ETC'
- config_sets:
  - fsl_adc_etc:
    - config:
      - clockConfig_t:
        - clockSource: 'BusInterfaceClock'
        - clockSourceFreq: 'BOARD_BootClockRUN'
        - clockPreDivider: '1'
      - dmaMode: 'kADC_ETC_TrigDMAWithLatchedSignal'
    - tscConfig:
      - enableTSCBypass: 'true'
      - enableTSC0Trigger: 'false'
      - TSC0triggerPriority: '0'
      - enableTSC1Trigger: 'false'
      - TSC1triggerPriority: '0'
    - triggers_config:
      - 0:
        - triggerNameValue: 'TC_0'
        - initializeTrigger: 'true'
        - trigger: 'XBAR0_TRIG.0'
        - triggerPriority: '0'
        - enableSWTriggerMode: 'true'
        - enableSyncMode: 'false'
        - enableDMA: 'false'
        - initialDelay_str: '0'
        - sampleIntervalDelay_str: '1024'
        - triggerChain:
          - 0:
            - enableB2BMode: 'false'
            - ADCHCRegisterSelect: '0'
            - channelNumber: 'ADC1.IN.0'
            - e_InterruptEnable: 'kADC_ETC_Done0InterruptEnable'
          - 1:
            - enableB2BMode: 'false'
            - ADCHCRegisterSelect: '0'
            - channelNumber: 'ADC1.IN.15'
            - e_InterruptEnable: 'kADC_ETC_Done0InterruptEnable'
    - enableInterrupt: 'true'
    - adc_etc_interrupt_0:
      - IRQn: 'ADC_ETC_IRQ0_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - adc_etc_interrupt_err:
      - IRQn: 'ADC_ETC_ERROR_IRQ_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
/* ADC_ETC configuration */
const adc_etc_config_t ADC_ETC_config = {
  .clockPreDivider = 1,
  .dmaMode = kADC_ETC_TrigDMAWithLatchedSignal,
  .enableTSCBypass = true,
  .enableTSC0Trigger = false,
  .enableTSC1Trigger = false,
  .TSC0triggerPriority = 0,
  .TSC1triggerPriority = 0,
  .XBARtriggerMask = 1
};
/* ADC_ETC triggers configuration */
const adc_etc_trigger_config_t ADC_ETC_trigger_config[1] = {
  {
    .triggerPriority = 0,
    .enableSWTriggerMode = true,
    .enableSyncMode = false,
    .initialDelay = 0,
    .sampleIntervalDelay = 1024,
    .triggerChainLength = 1
  }
};
/* ADC_ETC chain configurations for appropriate (see name of these arrays) trigger configuration */
const adc_etc_trigger_chain_config_t ADC_ETC_TC_0_chain_config[2] = {
  {
    .enableB2BMode = false,
    .ADCHCRegisterSelect = 1,
    .ADCChannelSelect = 0,
    .InterruptEnable = kADC_ETC_Done0InterruptEnable,
  },
  {
    .enableB2BMode = false,
    .ADCHCRegisterSelect = 1,
    .ADCChannelSelect = 15,
    .InterruptEnable = kADC_ETC_Done0InterruptEnable,
  }
};

static void ADC_ETC_init(void) {
  /* ADC_ETC initialization */
  ADC_ETC_Init(ADC_ETC_PERIPHERAL, &ADC_ETC_config);
  /* Initialize ADC_ETC trigger 0. */
  ADC_ETC_SetTriggerConfig(ADC_ETC_PERIPHERAL, ADC_ETC_TC_0_TG, &ADC_ETC_trigger_config[ADC_ETC_TC_0]);
  /* Initialize ADC_ETC chain configuration for trigger 0. */
  ADC_ETC_SetTriggerChainConfig(ADC_ETC_PERIPHERAL, ADC_ETC_TC_0_TG, 0U, &ADC_ETC_TC_0_chain_config[0]);
  /* Initialize ADC_ETC chain configuration for trigger 0. */
  ADC_ETC_SetTriggerChainConfig(ADC_ETC_PERIPHERAL, ADC_ETC_TC_0_TG, 1U, &ADC_ETC_TC_0_chain_config[1]);
  /* Enable interrupt ADC_ETC_IRQ0_IRQn request in the NVIC. */
  EnableIRQ(ADC_ETC_ADC_ETC_0_IRQN);
  /* Enable interrupt ADC_ETC_ERROR_IRQ_IRQn request in the NVIC. */
  EnableIRQ(ADC_ETC_ADC_ETC_ERROR_IRQN);
}

/***********************************************************************************************************************
 * GPT1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'GPT1'
- type: 'gpt'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'gpt_e92a0cbd07e389b82a1d19b05eb9fdda'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'GPT1'
- config_sets:
  - fsl_gpt:
    - gpt_config:
      - clockSource: 'kGPT_ClockSource_Periph'
      - clockSourceFreq: 'BOARD_BootClockRUN'
      - oscDivider: '1'
      - divider: '1'
      - enableFreeRun: 'false'
      - enableRunInWait: 'true'
      - enableRunInStop: 'true'
      - enableRunInDoze: 'false'
      - enableRunInDbg: 'false'
      - enableMode: 'true'
    - input_capture_channels: []
    - output_compare_channels:
      - 0:
        - channel: 'kGPT_OutputCompare_Channel1'
        - mode: 'kGPT_OutputOperation_Disconnected'
        - compare_value_str: '255'
    - interrupt_requests: ''
    - isInterruptEnabled: 'true'
    - interrupt:
      - IRQn: 'GPT1_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - EnableTimerInInit: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const gpt_config_t GPT1_config = {
  .clockSource = kGPT_ClockSource_Periph,
  .divider = 1,
  .enableFreeRun = false,
  .enableRunInWait = true,
  .enableRunInStop = true,
  .enableRunInDoze = false,
  .enableRunInDbg = false,
  .enableMode = true
};

static void GPT1_init(void) {
  /* GPT device and channels initialization */
  GPT_Init(GPT1_PERIPHERAL, &GPT1_config);
  GPT_SetOscClockDivider(GPT1_PERIPHERAL, 1);
  GPT_SetOutputCompareValue(GPT1_PERIPHERAL, kGPT_OutputCompare_Channel1, 255);
  GPT_SetOutputOperationMode(GPT1_PERIPHERAL, kGPT_OutputCompare_Channel1, kGPT_OutputOperation_Disconnected);
  /* Enable GPT interrupt sources */
  GPT_EnableInterrupts(GPT1_PERIPHERAL, 0);
  /* Enable interrupt GPT1_IRQn request in the NVIC. */
  EnableIRQ(GPT1_GPT_IRQN);
}

/***********************************************************************************************************************
 * GPT2 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'GPT2'
- type: 'gpt'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'gpt_e92a0cbd07e389b82a1d19b05eb9fdda'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'GPT2'
- config_sets:
  - fsl_gpt:
    - gpt_config:
      - clockSource: 'kGPT_ClockSource_Periph'
      - clockSourceFreq: 'BOARD_BootClockRUN'
      - oscDivider: '1'
      - divider: '1'
      - enableFreeRun: 'false'
      - enableRunInWait: 'true'
      - enableRunInStop: 'true'
      - enableRunInDoze: 'false'
      - enableRunInDbg: 'false'
      - enableMode: 'true'
    - input_capture_channels: []
    - output_compare_channels:
      - 0:
        - channel: 'kGPT_OutputCompare_Channel1'
        - mode: 'kGPT_OutputOperation_Disconnected'
        - compare_value_str: '255'
    - interrupt_requests: ''
    - isInterruptEnabled: 'true'
    - interrupt:
      - IRQn: 'GPT2_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - EnableTimerInInit: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const gpt_config_t GPT2_config = {
  .clockSource = kGPT_ClockSource_Periph,
  .divider = 1,
  .enableFreeRun = false,
  .enableRunInWait = true,
  .enableRunInStop = true,
  .enableRunInDoze = false,
  .enableRunInDbg = false,
  .enableMode = true
};

static void GPT2_init(void) {
  /* GPT device and channels initialization */
  GPT_Init(GPT2_PERIPHERAL, &GPT2_config);
  GPT_SetOscClockDivider(GPT2_PERIPHERAL, 1);
  GPT_SetOutputCompareValue(GPT2_PERIPHERAL, kGPT_OutputCompare_Channel1, 255);
  GPT_SetOutputOperationMode(GPT2_PERIPHERAL, kGPT_OutputCompare_Channel1, kGPT_OutputOperation_Disconnected);
  /* Enable GPT interrupt sources */
  GPT_EnableInterrupts(GPT2_PERIPHERAL, 0);
  /* Enable interrupt GPT2_IRQn request in the NVIC. */
  EnableIRQ(GPT2_GPT_IRQN);
}

/***********************************************************************************************************************
 * LPI2C1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'LPI2C1'
- type: 'lpi2c'
- mode: 'master'
- custom_name_enabled: 'false'
- type_id: 'lpi2c_db68d4f4f06a22e25ab51fe9bd6db4d2'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'LPI2C1'
- config_sets:
  - main:
    - clockSource: 'Lpi2cClock'
    - clockSourceFreq: 'BOARD_BootClockRUN'
    - interrupt:
      - IRQn: 'LPI2C1_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - quick_selection: 'qs_interrupt'
  - master:
    - mode: 'transfer'
    - config:
      - enableMaster: 'true'
      - enableDoze: 'true'
      - debugEnable: 'false'
      - ignoreAck: 'false'
      - pinConfig: 'kLPI2C_2PinOpenDrain'
      - baudRate_Hz: '100000'
      - busIdleTimeout_ns: '0'
      - pinLowTimeout_ns: '0'
      - sdaGlitchFilterWidth_ns: '0'
      - sclGlitchFilterWidth_ns: '0'
      - hostRequest:
        - enable: 'false'
        - source: 'kLPI2C_HostRequestExternalPin'
        - polarity: 'kLPI2C_HostRequestPinActiveHigh'
      - edmaRequestSources: ''
    - transfer:
      - blocking: 'true'
      - flags: ''
      - slaveAddress: '0'
      - direction: 'kLPI2C_Write'
      - subaddress: '0'
      - subaddressSize: '1'
      - dataSize: '2'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const lpi2c_master_config_t LPI2C1_masterConfig = {
  .enableMaster = true,
  .enableDoze = true,
  .debugEnable = false,
  .ignoreAck = false,
  .pinConfig = kLPI2C_2PinOpenDrain,
  .baudRate_Hz = 100000,
  .busIdleTimeout_ns = 0,
  .pinLowTimeout_ns = 0,
  .sdaGlitchFilterWidth_ns = 0,
  .sclGlitchFilterWidth_ns = 0,
  .hostRequest = {
    .enable = false,
    .source = kLPI2C_HostRequestExternalPin,
    .polarity = kLPI2C_HostRequestPinActiveHigh
  }
};
lpi2c_master_transfer_t LPI2C1_masterTransfer = {
  .flags = kLPI2C_TransferDefaultFlag,
  .slaveAddress = 0,
  .direction = kLPI2C_Write,
  .subaddress = 0,
  .subaddressSize = 1,
  .data = LPI2C1_masterBuffer,
  .dataSize = 2
};
uint8_t LPI2C1_masterBuffer[LPI2C1_MASTER_BUFFER_SIZE];

static void LPI2C1_init(void) {
  LPI2C_MasterInit(LPI2C1_PERIPHERAL, &LPI2C1_masterConfig, LPI2C1_CLOCK_FREQ);
}

/***********************************************************************************************************************
 * LPI2C3 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'LPI2C3'
- type: 'lpi2c'
- mode: 'master'
- custom_name_enabled: 'false'
- type_id: 'lpi2c_db68d4f4f06a22e25ab51fe9bd6db4d2'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'LPI2C3'
- config_sets:
  - main:
    - clockSource: 'Lpi2cClock'
    - clockSourceFreq: 'BOARD_BootClockRUN'
    - interrupt:
      - IRQn: 'LPI2C3_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
  - master:
    - mode: 'transfer'
    - config:
      - enableMaster: 'true'
      - enableDoze: 'true'
      - debugEnable: 'false'
      - ignoreAck: 'false'
      - pinConfig: 'kLPI2C_2PinOpenDrain'
      - baudRate_Hz: '100000'
      - busIdleTimeout_ns: '0'
      - pinLowTimeout_ns: '0'
      - sdaGlitchFilterWidth_ns: '0'
      - sclGlitchFilterWidth_ns: '0'
      - hostRequest:
        - enable: 'false'
        - source: 'kLPI2C_HostRequestExternalPin'
        - polarity: 'kLPI2C_HostRequestPinActiveHigh'
      - edmaRequestSources: ''
    - transfer:
      - blocking: 'false'
      - flags: ''
      - slaveAddress: '0'
      - direction: 'kLPI2C_Write'
      - subaddress: '0'
      - subaddressSize: '1'
      - dataSize: '1'
      - callback:
        - name: ''
        - userData: ''
    - quick_selection: 'qs_master_transfer'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const lpi2c_master_config_t LPI2C3_masterConfig = {
  .enableMaster = true,
  .enableDoze = true,
  .debugEnable = false,
  .ignoreAck = false,
  .pinConfig = kLPI2C_2PinOpenDrain,
  .baudRate_Hz = 100000,
  .busIdleTimeout_ns = 0,
  .pinLowTimeout_ns = 0,
  .sdaGlitchFilterWidth_ns = 0,
  .sclGlitchFilterWidth_ns = 0,
  .hostRequest = {
    .enable = false,
    .source = kLPI2C_HostRequestExternalPin,
    .polarity = kLPI2C_HostRequestPinActiveHigh
  }
};
lpi2c_master_transfer_t LPI2C3_masterTransfer = {
  .flags = kLPI2C_TransferDefaultFlag,
  .slaveAddress = 0,
  .direction = kLPI2C_Write,
  .subaddress = 0,
  .subaddressSize = 1,
  .data = LPI2C3_masterBuffer,
  .dataSize = 1
};
lpi2c_master_handle_t LPI2C3_masterHandle;
uint8_t LPI2C3_masterBuffer[LPI2C3_MASTER_BUFFER_SIZE];

static void LPI2C3_init(void) {
  LPI2C_MasterInit(LPI2C3_PERIPHERAL, &LPI2C3_masterConfig, LPI2C3_CLOCK_FREQ);
  LPI2C_MasterTransferCreateHandle(LPI2C3_PERIPHERAL, &LPI2C3_masterHandle, NULL, NULL);
}

/***********************************************************************************************************************
 * LPSPI1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'LPSPI1'
- type: 'lpspi'
- mode: 'polling'
- custom_name_enabled: 'false'
- type_id: 'lpspi_6e21a1e0a09f0a012d683c4f91752db8'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'LPSPI1'
- config_sets:
  - main:
    - mode: 'kLPSPI_Master'
    - clockSource: 'LpspiClock'
    - clockSourceFreq: 'BOARD_BootClockRUN'
    - master:
      - baudRate: '500000'
      - bitsPerFrame: '8'
      - cpol: 'kLPSPI_ClockPolarityActiveHigh'
      - cpha: 'kLPSPI_ClockPhaseFirstEdge'
      - direction: 'kLPSPI_MsbFirst'
      - pcsToSckDelayInNanoSec: '1000'
      - lastSckToPcsDelayInNanoSec: '1000'
      - betweenTransferDelayInNanoSec: '1000'
      - whichPcs: 'kLPSPI_Pcs0'
      - pcsActiveHighOrLow: 'kLPSPI_PcsActiveLow'
      - pinCfg: 'kLPSPI_SdiInSdoOut'
      - dataOutConfig: 'kLpspiDataOutRetained'
    - set_FifoWaterMarks: 'true'
    - fifoWaterMarks:
      - txWatermark: '15'
      - rxWatermark: '15'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const lpspi_master_config_t LPSPI1_config = {
  .baudRate = 500000,
  .bitsPerFrame = 8,
  .cpol = kLPSPI_ClockPolarityActiveHigh,
  .cpha = kLPSPI_ClockPhaseFirstEdge,
  .direction = kLPSPI_MsbFirst,
  .pcsToSckDelayInNanoSec = 1000,
  .lastSckToPcsDelayInNanoSec = 1000,
  .betweenTransferDelayInNanoSec = 1000,
  .whichPcs = kLPSPI_Pcs0,
  .pcsActiveHighOrLow = kLPSPI_PcsActiveLow,
  .pinCfg = kLPSPI_SdiInSdoOut,
  .dataOutConfig = kLpspiDataOutRetained
};

static void LPSPI1_init(void) {
  LPSPI_MasterInit(LPSPI1_PERIPHERAL, &LPSPI1_config, LPSPI1_CLOCK_FREQ);
  /* Set the transmit and receive FIFO watermarks */
  LPSPI_SetFifoWatermarks(LPSPI1_PERIPHERAL, LPSPI1_TX_FIFO_WATERMARK, LPSPI1_RX_FIFO_WATERMARK);
}

/***********************************************************************************************************************
 * LPSPI3 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'LPSPI3'
- type: 'lpspi'
- mode: 'interrupt'
- custom_name_enabled: 'false'
- type_id: 'lpspi_6e21a1e0a09f0a012d683c4f91752db8'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'LPSPI3'
- config_sets:
  - interrupt:
    - interrupt_sources: ''
    - interrupt:
      - IRQn: 'LPSPI3_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - quick_selection: 'qs_interrupt'
  - main:
    - mode: 'kLPSPI_Master'
    - clockSource: 'LpspiClock'
    - clockSourceFreq: 'BOARD_BootClockRUN'
    - master:
      - baudRate: '500000'
      - bitsPerFrame: '8'
      - cpol: 'kLPSPI_ClockPolarityActiveHigh'
      - cpha: 'kLPSPI_ClockPhaseFirstEdge'
      - direction: 'kLPSPI_MsbFirst'
      - pcsToSckDelayInNanoSec: '1000'
      - lastSckToPcsDelayInNanoSec: '1000'
      - betweenTransferDelayInNanoSec: '1000'
      - whichPcs: 'kLPSPI_Pcs0'
      - pcsActiveHighOrLow: 'kLPSPI_PcsActiveLow'
      - pinCfg: 'kLPSPI_SdiInSdoOut'
      - dataOutConfig: 'kLpspiDataOutRetained'
    - set_FifoWaterMarks: 'false'
    - fifoWaterMarks:
      - txWatermark: '0'
      - rxWatermark: '0'
    - quick_selection: 'qs_master'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const lpspi_master_config_t LPSPI3_config = {
  .baudRate = 500000,
  .bitsPerFrame = 8,
  .cpol = kLPSPI_ClockPolarityActiveHigh,
  .cpha = kLPSPI_ClockPhaseFirstEdge,
  .direction = kLPSPI_MsbFirst,
  .pcsToSckDelayInNanoSec = 1000,
  .lastSckToPcsDelayInNanoSec = 1000,
  .betweenTransferDelayInNanoSec = 1000,
  .whichPcs = kLPSPI_Pcs0,
  .pcsActiveHighOrLow = kLPSPI_PcsActiveLow,
  .pinCfg = kLPSPI_SdiInSdoOut,
  .dataOutConfig = kLpspiDataOutRetained
};

static void LPSPI3_init(void) {
  LPSPI_MasterInit(LPSPI3_PERIPHERAL, &LPSPI3_config, LPSPI3_CLOCK_FREQ);
  /* Enable interrupt LPSPI3_IRQn request in the NVIC. */
  EnableIRQ(LPSPI3_IRQN);
}

/***********************************************************************************************************************
 * LPUART1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'LPUART1'
- type: 'lpuart'
- mode: 'interrupts'
- custom_name_enabled: 'false'
- type_id: 'lpuart_54a65a580e3462acdbacefd5299e0cac'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'LPUART1'
- config_sets:
  - lpuartConfig_t:
    - lpuartConfig:
      - clockSource: 'LpuartClock'
      - lpuartSrcClkFreq: 'BOARD_BootClockRUN'
      - baudRate_Bps: '115200'
      - parityMode: 'kLPUART_ParityDisabled'
      - dataBitsCount: 'kLPUART_EightDataBits'
      - isMsb: 'false'
      - stopBitCount: 'kLPUART_OneStopBit'
      - txFifoWatermark: '0'
      - rxFifoWatermark: '1'
      - enableRxRTS: 'false'
      - enableTxCTS: 'false'
      - txCtsSource: 'kLPUART_CtsSourcePin'
      - txCtsConfig: 'kLPUART_CtsSampleAtStart'
      - rxIdleType: 'kLPUART_IdleTypeStartBit'
      - rxIdleConfig: 'kLPUART_IdleCharacter1'
      - enableTx: 'true'
      - enableRx: 'true'
    - quick_selection: 'QuickSelection1'
  - interruptsCfg:
    - interrupts: ''
    - interrupt_vectors:
      - enable_rx_tx_irq: 'true'
      - interrupt_rx_tx:
        - IRQn: 'LPUART1_IRQn'
        - enable_interrrupt: 'enabled'
        - enable_priority: 'false'
        - priority: '0'
        - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const lpuart_config_t LPUART1_config = {
  .baudRate_Bps = 115200,
  .parityMode = kLPUART_ParityDisabled,
  .dataBitsCount = kLPUART_EightDataBits,
  .isMsb = false,
  .stopBitCount = kLPUART_OneStopBit,
  .txFifoWatermark = 0,
  .rxFifoWatermark = 1,
  .enableRxRTS = false,
  .enableTxCTS = false,
  .txCtsSource = kLPUART_CtsSourcePin,
  .txCtsConfig = kLPUART_CtsSampleAtStart,
  .rxIdleType = kLPUART_IdleTypeStartBit,
  .rxIdleConfig = kLPUART_IdleCharacter1,
  .enableTx = true,
  .enableRx = true
};

static void LPUART1_init(void) {
  LPUART_Init(LPUART1_PERIPHERAL, &LPUART1_config, LPUART1_CLOCK_SOURCE);
  LPUART_EnableInterrupts(LPUART1_PERIPHERAL, 0);
  /* Enable interrupt LPUART1_IRQn request in the NVIC. */
  EnableIRQ(LPUART1_SERIAL_RX_TX_IRQN);
}

/***********************************************************************************************************************
 * RTC initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'RTC'
- type: 'snvs_hp'
- mode: 'general'
- custom_name_enabled: 'true'
- type_id: 'snvs_hp_5fc0a925779e7e5f8b9bedf272c8d94e'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'SNVS'
- config_sets:
  - fsl_snvs_hp:
    - snvs_hp_config:
      - init: 'false'
      - hac:
        - set: 'false'
        - initialValue: '0'
        - load: 'false'
        - enable: 'false'
        - start: 'false'
    - initRTC: 'true'
    - snvs_hp_rtc_config:
      - rtcCalEnable: 'false'
      - rtcCalValueInt: '0'
      - periodicInterruptFreq: '0'
      - start: 'false'
      - callTimeSynchronize: 'false'
      - setDateTime: 'false'
    - interruptsCfg:
      - interruptSources: ''
      - isInterruptEnabled: 'false'
      - interrupt:
        - IRQn: 'SNVS_HP_WRAPPER_IRQn'
        - enable_interrrupt: 'enabled'
        - enable_priority: 'false'
        - priority: '0'
        - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const snvs_hp_rtc_config_t RTC_config = {
  .rtcCalEnable = false,
  .rtcCalValue = 0,
  .periodicInterruptFreq = 0
};

static void RTC_init(void) {
  /* SNVS HP RTC initialization */
  SNVS_HP_RTC_Init(RTC_PERIPHERAL, &RTC_config);
}

/***********************************************************************************************************************
 * RTWDOG initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'RTWDOG'
- type: 'rtwdog'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'rtwdog_04d8f6604a79500facf56c1a1d0a7215'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'RTWDOG'
- config_sets:
  - fsl_rtwdog:
    - rtwdogConfig:
      - clockSource: 'kRTWDOG_ClockSource1'
      - clockSourceFreq: 'BOARD_BootClockRUN'
      - prescaler: 'kRTWDOG_ClockPrescalerDivide256'
      - testMode: 'kRTWDOG_TestModeDisabled'
      - enableUpdate: 'true'
      - timeoutValue_str: '1024'
      - enableWindowMode: 'false'
      - windowValue_str: '0'
      - enableRtwdog: 'false'
      - workMode:
        - enableWait: 'true'
        - enableStop: 'false'
        - enableDebug: 'false'
    - interrupt_config:
      - enableInterrupt: 'true'
      - interrupt_vectors:
        - enable_irq: 'true'
        - interrupt:
          - IRQn: 'RTWDOG_IRQn'
          - enable_interrrupt: 'enabled'
          - enable_priority: 'false'
          - priority: '0'
          - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const rtwdog_config_t RTWDOG_config = {
  .clockSource = kRTWDOG_ClockSource1,
  .prescaler = kRTWDOG_ClockPrescalerDivide256,
  .testMode = kRTWDOG_TestModeDisabled,
  .enableUpdate = true,
  .timeoutValue = 1024,
  .enableWindowMode = false,
  .windowValue = 0,
  .enableRtwdog = false,
  .workMode = {
    .enableWait = true,
    .enableStop = false,
    .enableDebug = false
  },
  .enableInterrupt = true
};

static void RTWDOG_init(void) {
  /* RTWDOG peripheral initialization */
  RTWDOG_Init(RTWDOG_PERIPHERAL, &RTWDOG_config);
  /* Enable interrupt RTWDOG_IRQn request in the NVIC. */
  EnableIRQ(RTWDOG_IRQN);
}

/***********************************************************************************************************************
 * SAI1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'SAI1'
- type: 'sai'
- mode: 'edma'
- custom_name_enabled: 'false'
- type_id: 'sai_37a0d4b4ecc2db8ea149dbe2026c6550'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'SAI1'
- config_sets:
  - fsl_sai:
    - usage: 'record_playback'
    - signal_config:
      - 0:
        - sourceTx: 'Tx'
        - sourceRx: 'Tx'
      - 1:
        - sourceTx: 'Tx'
        - sourceRx: 'Tx'
    - syncSwapI: []
    - bclkTxSetting: []
    - bclkRxSetting: []
    - syncTxSetting: []
    - syncRxSetting: []
    - whole:
      - tx_group:
        - sai_transceiver:
          - bitClock:
            - modeM: 'master'
            - bitClockSource: 'kSAI_BclkSourceMclkOption1'
            - bitClockSourceFreq: 'custom:6144375'
            - bclkPolarityM: 'kSAI_PolarityActiveLow'
            - bclkInputDelayM: 'false'
          - frameSync:
            - modeM: 'master'
            - frameSyncWidthM: '16'
            - frameSyncPolarityM: 'kSAI_PolarityActiveLow'
            - frameSyncEarlyM: 'true'
          - sampleRate_Hz: 'kSAI_SampleRate16KHz'
          - channelMask: 'kSAI_Channel0Mask'
          - serialData:
            - dataMode: 'kSAI_DataPinStateOutputZero'
            - differentFirstWord: 'false'
            - sameDataWordLengthM: 'kSAI_WordWidth16bits'
            - dataOrder: 'kSAI_DataMSB'
            - dataFirstBitShiftedM: '16'
            - dataWordNumM: '2'
            - dataMasked_config:
              - dataMasked_L:
                - 0: 'false'
                - 1: 'false'
                - 2: 'false'
                - 3: 'false'
                - 4: 'false'
                - 5: 'false'
                - 6: 'false'
                - 7: 'false'
                - 8: 'false'
                - 9: 'false'
                - 10: 'false'
                - 11: 'false'
                - 12: 'false'
                - 13: 'false'
                - 14: 'false'
                - 15: 'false'
              - dataMasked_H:
                - 0: 'false'
                - 1: 'false'
                - 2: 'false'
                - 3: 'false'
                - 4: 'false'
                - 5: 'false'
                - 6: 'false'
                - 7: 'false'
                - 8: 'false'
                - 9: 'false'
                - 10: 'false'
                - 11: 'false'
                - 12: 'false'
                - 13: 'false'
                - 14: 'false'
                - 15: 'false'
          - fifo:
            - fifoWatermarkM: '16'
            - fifoPacking: 'kSAI_FifoPackingDisabled'
            - fifoContinueOneError: 'true'
        - edma_group:
          - enable_edma_channel: 'true'
          - edma_channel:
            - eDMAn: '0'
            - eDMA_source: 'kDmaRequestMuxSai1Tx'
            - enableTriggerPIT: 'false'
            - init_channel_priority: 'false'
            - edma_channel_Preemption:
              - enableChannelPreemption: 'false'
              - enablePreemptAbility: 'false'
              - channelPriority: '0'
            - enable_custom_name: 'false'
          - sai_edma_handle:
            - enable_custom_name: 'false'
            - init_callback: 'true'
            - callback_fcn: 'SAI1_SAI_Tx_eDMA_CallBack'
            - user_data: ''
      - rx_group:
        - sai_transceiver:
          - bitClock:
            - modeM: 'master'
            - bitClockSource: 'kSAI_BclkSourceMclkDiv'
            - bitClockSourceFreq: 'BOARD_BootClockRUN'
            - bclkPolarityM: 'kSAI_PolarityActiveLow'
            - bclkInputDelayM: 'false'
          - frameSync:
            - modeM: 'master'
            - frameSyncWidthM: '16'
            - frameSyncPolarityM: 'kSAI_PolarityActiveLow'
            - frameSyncEarlyM: 'true'
          - sampleRate_Hz: 'kSAI_SampleRate44100Hz'
          - channelMask: 'kSAI_Channel0Mask'
          - serialData:
            - dataMode: 'kSAI_DataPinStateTriState'
            - differentFirstWord: 'false'
            - sameDataWordLengthM: 'kSAI_WordWidth16bits'
            - dataOrder: 'kSAI_DataMSB'
            - dataFirstBitShiftedM: '16'
            - dataWordNumM: '2'
            - dataMasked_config:
              - dataMasked_L:
                - 0: 'false'
                - 1: 'false'
                - 2: 'false'
                - 3: 'false'
                - 4: 'false'
                - 5: 'false'
                - 6: 'false'
                - 7: 'false'
                - 8: 'false'
                - 9: 'false'
                - 10: 'false'
                - 11: 'false'
                - 12: 'false'
                - 13: 'false'
                - 14: 'false'
                - 15: 'false'
              - dataMasked_H:
                - 0: 'false'
                - 1: 'false'
                - 2: 'false'
                - 3: 'false'
                - 4: 'false'
                - 5: 'false'
                - 6: 'false'
                - 7: 'false'
                - 8: 'false'
                - 9: 'false'
                - 10: 'false'
                - 11: 'false'
                - 12: 'false'
                - 13: 'false'
                - 14: 'false'
                - 15: 'false'
          - fifo:
            - fifoWatermarkM: '16'
            - fifoPacking: 'kSAI_FifoPackingDisabled'
            - fifoContinueOneError: 'false'
        - edma_group:
          - enable_edma_channel: 'true'
          - edma_channel:
            - eDMAn: '1'
            - eDMA_source: 'kDmaRequestMuxSai1Rx'
            - enableTriggerPIT: 'false'
            - init_channel_priority: 'false'
            - edma_channel_Preemption:
              - enableChannelPreemption: 'false'
              - enablePreemptAbility: 'false'
              - channelPriority: '0'
            - enable_custom_name: 'false'
          - sai_edma_handle:
            - enable_custom_name: 'false'
            - init_callback: 'true'
            - callback_fcn: 'SAI1_SAI_Rx_eDMA_CallBack'
            - user_data: ''
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
/* SAI1 Tx configuration */
sai_transceiver_t SAI1_Tx_config = {
  .masterSlave = kSAI_Master,
  .bitClock = {
    .bclkSrcSwap = false,
    .bclkSource = kSAI_BclkSourceMclkOption1,
    .bclkPolarity = kSAI_PolarityActiveLow,
    .bclkInputDelay = false
  },
  .frameSync = {
    .frameSyncWidth = 16U,
    .frameSyncPolarity = kSAI_PolarityActiveLow,
    .frameSyncEarly = true,
  },
  .syncMode = kSAI_ModeAsync,
  .channelMask = kSAI_Channel0Mask,
  .startChannel = 0U,
  .endChannel = 0U,
  .channelNums = 1U,
  .serialData = {
    .dataMode = kSAI_DataPinStateOutputZero,
    .dataWord0Length = (uint8_t)kSAI_WordWidth16bits,
    .dataWordNLength = (uint8_t)kSAI_WordWidth16bits,
    .dataWordLength = (uint8_t)kSAI_WordWidth16bits,
    .dataOrder = kSAI_DataMSB,
    .dataFirstBitShifted = 16U,
    .dataWordNum = 2U,
    .dataMaskedWord = 0x0U
  },
  .fifo = {
    .fifoWatermark = 16U,
    .fifoPacking = kSAI_FifoPackingDisabled,
    .fifoContinueOneError = true
  }
};
/* SAI1 Rx configuration */
sai_transceiver_t SAI1_Rx_config = {
  .masterSlave = kSAI_Master,
  .bitClock = {
    .bclkSrcSwap = false,
    .bclkSource = kSAI_BclkSourceMclkOption1,
    .bclkPolarity = kSAI_PolarityActiveLow,
    .bclkInputDelay = false
  },
  .frameSync = {
    .frameSyncWidth = 16U,
    .frameSyncPolarity = kSAI_PolarityActiveLow,
    .frameSyncEarly = true,
  },
  .syncMode = kSAI_ModeSync,
  .channelMask = kSAI_Channel0Mask,
  .startChannel = 0U,
  .endChannel = 0U,
  .channelNums = 1U,
  .serialData = {
    .dataMode = kSAI_DataPinStateTriState,
    .dataWord0Length = (uint8_t)kSAI_WordWidth16bits,
    .dataWordNLength = (uint8_t)kSAI_WordWidth16bits,
    .dataWordLength = (uint8_t)kSAI_WordWidth16bits,
    .dataOrder = kSAI_DataMSB,
    .dataFirstBitShifted = 16U,
    .dataWordNum = 2U,
    .dataMaskedWord = 0x0U
  },
  .fifo = {
    .fifoWatermark = 16U,
    .fifoPacking = kSAI_FifoPackingDisabled,
    .fifoContinueOneError = false
  }
};
edma_handle_t SAI1_TX_Handle;
edma_handle_t SAI1_RX_Handle;
sai_edma_handle_t SAI1_SAI_Tx_eDMA_Handle;
sai_edma_handle_t SAI1_SAI_Rx_eDMA_Handle;

static void SAI1_init(void) {
  /* Set the source kDmaRequestMuxSai1Tx request in the DMAMUX */
  DMAMUX_SetSource(SAI1_TX_DMAMUX_BASEADDR, SAI1_TX_DMA_CHANNEL, SAI1_TX_DMA_REQUEST);
  /* Enable the channel 0 in the DMAMUX */
  DMAMUX_EnableChannel(SAI1_TX_DMAMUX_BASEADDR, SAI1_TX_DMA_CHANNEL);
  /* Set the source kDmaRequestMuxSai1Rx request in the DMAMUX */
  DMAMUX_SetSource(SAI1_RX_DMAMUX_BASEADDR, SAI1_RX_DMA_CHANNEL, SAI1_RX_DMA_REQUEST);
  /* Enable the channel 1 in the DMAMUX */
  DMAMUX_EnableChannel(SAI1_RX_DMAMUX_BASEADDR, SAI1_RX_DMA_CHANNEL);
  /* Create the eDMA SAI1_TX_Handle handle */
  EDMA_CreateHandle(&SAI1_TX_Handle, SAI1_TX_DMA_BASEADDR, SAI1_TX_DMA_CHANNEL);
  /* Create the eDMA SAI1_RX_Handle handle */
  EDMA_CreateHandle(&SAI1_RX_Handle, SAI1_RX_DMA_BASEADDR, SAI1_RX_DMA_CHANNEL);
  /* Initialize SAI clock gate */
  SAI_Init(SAI1_PERIPHERAL);
  /* Create the SAI Tx eDMA handle */
  SAI_TransferTxCreateHandleEDMA(SAI1_PERIPHERAL, &SAI1_SAI_Tx_eDMA_Handle, SAI1_SAI_Tx_eDMA_CallBack, NULL, &SAI1_TX_Handle);
  /* Create the SAI Rx eDMA handle */
  SAI_TransferRxCreateHandleEDMA(SAI1_PERIPHERAL, &SAI1_SAI_Rx_eDMA_Handle, SAI1_SAI_Rx_eDMA_CallBack, NULL, &SAI1_RX_Handle);
  /* Configures SAI Tx sub-module functionality */
  SAI_TransferTxSetConfigEDMA(SAI1_PERIPHERAL, &SAI1_SAI_Tx_eDMA_Handle, &SAI1_Tx_config);
  /* Configures SAI Rx sub-module functionality */
  SAI_TransferRxSetConfigEDMA(SAI1_PERIPHERAL, &SAI1_SAI_Rx_eDMA_Handle, &SAI1_Rx_config);
  /* Set up SAI Tx bitclock rate by calculation of divider. */
  SAI_TxSetBitClockRate(SAI1_PERIPHERAL, SAI1_TX_BCLK_SOURCE_CLOCK_HZ, SAI1_TX_SAMPLE_RATE, SAI1_TX_WORD_WIDTH, SAI1_TX_WORDS_PER_FRAME);
  /* Set up SAI Rx bitclock rate by calculation of divider. */
  SAI_RxSetBitClockRate(SAI1_PERIPHERAL, SAI1_RX_BCLK_SOURCE_CLOCK_HZ, SAI1_RX_SAMPLE_RATE, SAI1_RX_WORD_WIDTH, SAI1_RX_WORDS_PER_FRAME);
}

/***********************************************************************************************************************
 * TRNG1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'TRNG1'
- type: 'TRNG'
- mode: 'General'
- custom_name_enabled: 'true'
- type_id: 'trng_dd5b2a6f14d45ca091cf6c9a38560d5e'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'TRNG'
- config_sets:
  - fsl_trng:
    - settings_trng_config_t:
      - clockMode: 'kTRNG_ClockModeRingOscillator'
      - struct_ring_oscillator:
        - ringOscDiv: 'kTRNG_RingOscDiv0'
        - sampleMode: 'kTRNG_SampleModeRaw'
      - entropyDelay: '3200'
      - sampleSize: '2500'
      - sparseBitLimit: '63'
      - retryCount: '1'
      - lock: 'false'
      - struct_statistical_checks:
        - longRunMaxLimit: '34'
        - monobitLimit:
          - maximum: '1384'
          - minimum: '1116'
        - runBit1Limit:
          - maximum: '405'
          - minimum: '227'
        - runBit2Limit:
          - maximum: '220'
          - minimum: '98'
        - runBit3Limit:
          - maximum: '125'
          - minimum: '37'
        - runBit4Limit:
          - maximum: '75'
          - minimum: '11'
        - runBit5Limit:
          - maximum: '47'
          - minimum: '1'
        - runBit6PlusLimit:
          - maximum: '47'
          - minimum: '1'
        - pokerLimit:
          - maximum: '26912'
          - minimum: '24445'
        - frequencyCountLimit:
          - maximum: '25600'
          - minimum: '1600'
    - quick_selection: 'Default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const trng_config_t TRNG1_config = {
  .lock = false,
  .clockMode = kTRNG_ClockModeRingOscillator,
  .ringOscDiv = kTRNG_RingOscDiv0,
  .sampleMode = kTRNG_SampleModeRaw,
  .entropyDelay = 3200,
  .sampleSize = 2500,
  .sparseBitLimit = 63,
  .retryCount = 1,
  .longRunMaxLimit = 34,
  .monobitLimit = {
    .maximum = 1384,
    .minimum = 1116
  },
  .runBit1Limit = {
    .maximum = 405,
    .minimum = 227
  },
  .runBit2Limit = {
    .maximum = 220,
    .minimum = 98
  },
  .runBit3Limit = {
    .maximum = 125,
    .minimum = 37
  },
  .runBit4Limit = {
    .maximum = 75,
    .minimum = 11
  },
  .runBit5Limit = {
    .maximum = 47,
    .minimum = 1
  },
  .runBit6PlusLimit = {
    .maximum = 47,
    .minimum = 1
  },
  .pokerLimit = {
    .maximum = 26912,
    .minimum = 24445
  },
  .frequencyCountLimit = {
    .maximum = 25600,
    .minimum = 1600
  }
};

static void TRNG1_init(void) {
  /* Initialize TRNG. */
  TRNG_Init(TRNG1_PERIPHERAL, &TRNG1_config);
}

/***********************************************************************************************************************
 * WDOG1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'WDOG1'
- type: 'wdog01'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'wdog01_510a9c5ba7e0ced8deac305549f23fa9'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'WDOG1'
- config_sets:
  - fsl_wdog:
    - wdogConfig:
      - clockSource: 'LowFreqClock'
      - timeoutValue_str: '8s'
      - enablePowerDown: 'false'
      - softwareResetExtension: 'false'
      - enableTimeOutAssert: 'false'
      - enableWdog: 'false'
      - workMode:
        - enableWait: 'false'
        - enableStop: 'false'
        - enableDebug: 'false'
    - interrupt_config:
      - enableInterrupt: 'true'
      - interruptTimeValue_str: '4'
      - interrupt_vectors:
        - enable_irq: 'false'
        - interrupt:
          - IRQn: 'WDOG1_IRQn'
          - enable_interrrupt: 'enabled'
          - enable_priority: 'false'
          - priority: '0'
          - enable_custom_name: 'false'
    - signals: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const wdog_config_t WDOG1_config = {
  .timeoutValue = 15,
  .enablePowerDown = false,
  .softwareResetExtension = false,
  .enableTimeOutAssert = false,
  .enableWdog = false,
  .workMode = {
    .enableWait = false,
    .enableStop = false,
    .enableDebug = false
  }, 
  .enableInterrupt = true,
  .interruptTimeValue = 3
};

static void WDOG1_init(void) {
  /* WDOG peripheral initialization */
  WDOG_Init(WDOG1_PERIPHERAL, &WDOG1_config);
}

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
void BOARD_InitPeripherals(void)
{
  /* Global initialization */
  DMAMUX_Init(DMA0_DMAMUX_BASEADDR);
  EDMA_Init(DMA0_DMA_BASEADDR, &DMA0_config);

  /* Initialize components */
  DMA0_init();
  ADC1_init();
  ADC_ETC_init();
  GPT1_init();
  GPT2_init();
  LPI2C1_init();
  LPI2C3_init();
  LPSPI1_init();
  LPSPI3_init();
  LPUART1_init();
  RTC_init();
  RTWDOG_init();
  SAI1_init();
  TRNG1_init();
  WDOG1_init();
}

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void)
{
  BOARD_InitPeripherals();
}
