/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
  kPIN_MUX_DirectionInput = 0U,         /* Input direction */
  kPIN_MUX_DirectionOutput = 1U,        /* Output direction */
  kPIN_MUX_DirectionInputOrOutput = 2U  /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/* GPIO_AD_B0_13 (coord L14), UART1_RXD */
/* Routed pin properties */
#define BOARD_UART1_RXD_PERIPHERAL                                       LPUART1   /*!< Peripheral name */
#define BOARD_UART1_RXD_SIGNAL                                                RX   /*!< Signal name */

/* GPIO_AD_B0_12 (coord K14), UART1_TXD */
/* Routed pin properties */
#define BOARD_UART1_TXD_PERIPHERAL                                       LPUART1   /*!< Peripheral name */
#define BOARD_UART1_TXD_SIGNAL                                                TX   /*!< Signal name */

/* GPIO_AD_B1_06 (coord J12), CSI_VSYNC/J35[18]/J22[2]/UART_TX */
/* Routed pin properties */
#define BOARD_CSI_VSYNC_PERIPHERAL                                        LPI2C3   /*!< Peripheral name */
#define BOARD_CSI_VSYNC_SIGNAL                                               SDA   /*!< Signal name */

/* GPIO_AD_B1_07 (coord K10), CSI_HSYNC/J35[16]/J22[1]/UART_RX */
/* Routed pin properties */
#define BOARD_CSI_HSYNC_PERIPHERAL                                        LPI2C3   /*!< Peripheral name */
#define BOARD_CSI_HSYNC_SIGNAL                                               SCL   /*!< Signal name */

/* GPIO_SD_B0_00 (coord J4), SD1_CMD/J24[6] */
/* Routed pin properties */
#define BOARD_SD1_CMD_PERIPHERAL                                          LPSPI1   /*!< Peripheral name */
#define BOARD_SD1_CMD_SIGNAL                                                 SCK   /*!< Signal name */

/* GPIO_SD_B0_01 (coord J3), SD1_CLK/J24[3] */
/* Routed pin properties */
#define BOARD_SD1_CLK_PERIPHERAL                                          LPSPI1   /*!< Peripheral name */
#define BOARD_SD1_CLK_SIGNAL                                                PCS0   /*!< Signal name */

/* GPIO_SD_B0_02 (coord J1), SD1_D0/J24[4]/SPI_MOSI/PWM */
/* Routed pin properties */
#define BOARD_SD1_D0_PERIPHERAL                                           LPSPI1   /*!< Peripheral name */
#define BOARD_SD1_D0_SIGNAL                                                  SDO   /*!< Signal name */

/* GPIO_SD_B0_03 (coord K1), SD1_D1/J24[5]/SPI_MISO */
/* Routed pin properties */
#define BOARD_SD1_D1_PERIPHERAL                                           LPSPI1   /*!< Peripheral name */
#define BOARD_SD1_D1_SIGNAL                                                  SDI   /*!< Signal name */

/* GPIO_EMC_01 (coord F3), SEMC_D1 */
/* Routed pin properties */
#define BOARD_SEMC_D1_PERIPHERAL                                          LPSPI2   /*!< Peripheral name */
#define BOARD_SEMC_D1_SIGNAL                                                PCS0   /*!< Signal name */

/* GPIO_EMC_00 (coord E3), SEMC_D0 */
/* Routed pin properties */
#define BOARD_SEMC_D0_PERIPHERAL                                          LPSPI2   /*!< Peripheral name */
#define BOARD_SEMC_D0_SIGNAL                                                 SCK   /*!< Signal name */

/* GPIO_EMC_03 (coord G4), SEMC_D3 */
/* Routed pin properties */
#define BOARD_SEMC_D3_PERIPHERAL                                          LPSPI2   /*!< Peripheral name */
#define BOARD_SEMC_D3_SIGNAL                                                 SDI   /*!< Signal name */

/* GPIO_EMC_02 (coord F4), SEMC_D2 */
/* Routed pin properties */
#define BOARD_SEMC_D2_PERIPHERAL                                          LPSPI2   /*!< Peripheral name */
#define BOARD_SEMC_D2_SIGNAL                                                 SDO   /*!< Signal name */

/* GPIO_AD_B1_11 (coord J13), SAI1_RX_BCLK/CSI_D6/J35[7]/J23[2] */
/* Routed pin properties */
#define BOARD_CSI_D6_PERIPHERAL                                             ADC2   /*!< Peripheral name */
#define BOARD_CSI_D6_SIGNAL                                                   IN   /*!< Signal name */
#define BOARD_CSI_D6_CHANNEL                                                  0U   /*!< Signal channel */

/* GPIO_AD_B1_10 (coord L13), SAI1_RX_SYNC/CSI_D7/J35[9]/J23[1] */
/* Routed pin properties */
#define BOARD_CSI_D7_PERIPHERAL                                             ADC1   /*!< Peripheral name */
#define BOARD_CSI_D7_SIGNAL                                                   IN   /*!< Signal name */
#define BOARD_CSI_D7_CHANNEL                                                 15U   /*!< Signal channel */

/* GPIO_EMC_10 (coord G1), SEMC_A1 */
/* Routed pin properties */
#define BOARD_SEMC_A1_PERIPHERAL                                         FLEXIO1   /*!< Peripheral name */
#define BOARD_SEMC_A1_SIGNAL                                                  IO   /*!< Signal name */
#define BOARD_SEMC_A1_CHANNEL                                                10U   /*!< Signal channel */

/* GPIO_EMC_27 (coord A2), SEMC_CKE */
/* Routed pin properties */
#define BOARD_SEMC_CKE_PERIPHERAL                                        FLEXIO1   /*!< Peripheral name */
#define BOARD_SEMC_CKE_SIGNAL                                                 IO   /*!< Signal name */
#define BOARD_SEMC_CKE_CHANNEL                                               13U   /*!< Signal channel */

/* GPIO_EMC_28 (coord D1), SEMC_WE */
/* Routed pin properties */
#define BOARD_SEMC_WE_PERIPHERAL                                         FLEXIO1   /*!< Peripheral name */
#define BOARD_SEMC_WE_SIGNAL                                                  IO   /*!< Signal name */
#define BOARD_SEMC_WE_CHANNEL                                                14U   /*!< Signal channel */

/* GPIO_EMC_29 (coord E1), SEMC_CS0 */
/* Routed pin properties */
#define BOARD_SEMC_CS0_PERIPHERAL                                        FLEXIO1   /*!< Peripheral name */
#define BOARD_SEMC_CS0_SIGNAL                                                 IO   /*!< Signal name */
#define BOARD_SEMC_CS0_CHANNEL                                               15U   /*!< Signal channel */

/* GPIO_AD_B1_09 (coord M13), SAI1_MCLK/CSI_D8/J35[11] */
/* Routed pin properties */
#define BOARD_CSI_D8_PERIPHERAL                                             SAI1   /*!< Peripheral name */
#define BOARD_CSI_D8_SIGNAL                                             sai_mclk   /*!< Signal name */

/* GPIO_AD_B1_14 (coord G12), SAI1_TX_BCLK/CSI_D3/J35[4]/U13[12] */
/* Routed pin properties */
#define BOARD_CSI_D3_PERIPHERAL                                             SAI1   /*!< Peripheral name */
#define BOARD_CSI_D3_SIGNAL                                          sai_tx_bclk   /*!< Signal name */

/* GPIO_AD_B1_12 (coord H12), SAI1_RXD/CSI_D5/J35[5]/U13[16] */
/* Routed pin properties */
#define BOARD_CSI_D5_PERIPHERAL                                             SAI1   /*!< Peripheral name */
#define BOARD_CSI_D5_SIGNAL                                         sai_rx_data0   /*!< Signal name */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
