Import('OS_ROOT')
Import('osconfig')
from build_tools import *

src = []
CPPDEFINES = []

pwd = PresentDir()

if IsDefined('BSP_USING_GPIO'):
    src += ['drv_gpio.c']

if  IsDefined('BSP_USING_LPUART'):
    src += ['drv_uart.c']

if  IsDefined('BSP_USING_HWTIMER'):
    src += ['drv_hwtimer.c']

if IsDefined('BSP_USING_RTC'):
    src += ['drv_rtc.c']

if  IsDefined('BSP_USING_SPI'):
    src += ['drv_spi.c']

if  IsDefined('BSP_USING_I2C'):
    src += ['drv_i2c.c']

if IsDefined('BSP_USING_WDT'):
    src += ['drv_wdt.c']

if IsDefined('BSP_USING_PWM'):
    src += ['drv_pwm.c']

if IsDefined('BSP_USING_ADC'):
    src += ['drv_adc.c']

if IsDefined('BSP_USING_CAN'):
    src += ['drv_can.c']
    
if IsDefined('BSP_USING_SDRAM'):
    src += ['drv_sdram.c']

if IsDefined('BSP_USING_LCD'):
    src += ['drv_lcd.c']

if IsDefined('BSP_USING_ETH'):
    src += ['drv_eth.c']

if IsDefined('BSP_USING_USB_DEVICE'):
    src += ['drv_usbd.c']
    src += Glob('usb/device/*.c')

if IsDefined('BSP_USING_USB_DEVICE'):
    src += Glob('usb/phy/*.c')
    CPPDEFINES += ['ENDIANNESS']
src += ['drv_common.c']

path =  [pwd,pwd + '/config']

group = AddCodeGroup('hal/drivers', src, depend = ['SOC_FAMILY_IMX'], CPPPATH = path, CPPDEFINES=CPPDEFINES)

Return('group')
