from build_tools import *

pwd = PresentDir()
src = Glob('*.c') + Glob('*.cpp')
CPPPATH = [pwd + '/../include']

group = AddCodeGroup('freertos_v8_2_0', src,
    depend = ['OS_USING_FREERTOS_API_V8_2_0'], CPPPATH = CPPPATH)

Return('group')
